In [871]:
import numpy as np
import pandas as pd
import re

In [ ]:
df = pd.read_csv("../data/raw/laptops_raw.csv")

In [873]:
df1 = df.copy()

In [874]:
pd.set_option("display.max_columns",None)
df1.head(5)

,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty
0,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,"₹1,89,990",84.0,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32 GB DDR5 RAM,1 TB SSD,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1 Year Warranty
1,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,"₹62,350",54.0,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16 GB LPDDR5 RAM,1 TB SSD,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1 Year Warranty
2,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,"₹34,990",51.0,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1 Year Warranty
3,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,"₹56,990",48.0,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16 GB RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty
4,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,"₹69,990",52.0,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1 Year Warranty

In [875]:
df1.isnull().sum()

model         0
price         0
rating        1
processor     8
cores        23
ram           3
storage       4
display       0
graphics     10
os            3
warranty      4
dtype: int64

In [876]:
df1[df1['rating'].isna()]

,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty
361,Asus ROG Strix G16 G614JU-N3526WS Gaming Lapto...,"₹1,08,990",NaN,Processor : 13th Gen Intel Core i5-13450HX Pro...,Processor : 13th Gen Intel Core i5-13450HX Pro...,NaN,【Software : Microsoft 365 Basic with 100GB Clo...,Display : 16-inch,Graphics : NVIDIA GeForce RTX 4050 Laptop GPU ...,Operating System : Windows 11 Home】,NaN

In [877]:
df1["price"]=df1["price"].str.replace("₹","").str.replace(",","")

In [878]:
brand=df1["model"].str.lower().str.strip().str.split(" ").str.get(0).str.replace("\u200e","",regex=False)

In [879]:
df1.insert(0,"brand",brand)

In [880]:
df1.head()

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84.0,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32 GB DDR5 RAM,1 TB SSD,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1 Year Warranty
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54.0,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16 GB LPDDR5 RAM,1 TB SSD,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1 Year Warranty
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51.0,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1 Year Warranty
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48.0,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16 GB RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52.0,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1 Year Warranty

In [881]:
df1["brand"].value_counts()

brand
lenovo       235
hp           225
asus         181
acer         103
msi           93
dell          76
apple         22
samsung       17
microsoft     12
infinix       10
gigabyte       7
alienware      7
motorola       5
ultimus        4
thomson        4
chuwi          3
primebook      3
colorful       2
walker         1
air            1
Name: count, dtype: int64

In [882]:
df1.head()

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84.0,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32 GB DDR5 RAM,1 TB SSD,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1 Year Warranty
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54.0,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16 GB LPDDR5 RAM,1 TB SSD,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1 Year Warranty
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51.0,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1 Year Warranty
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48.0,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16 GB RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52.0,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1 Year Warranty

In [883]:
df1.isna().sum()

brand         0
model         0
price         0
rating        1
processor     8
cores        23
ram           3
storage       4
display       0
graphics     10
os            3
warranty      4
dtype: int64

In [884]:
df1=df1.dropna(subset=["rating"])

In [885]:
df1["rating"]=df1["rating"].astype(int)

In [886]:
df1.head()

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32 GB DDR5 RAM,1 TB SSD,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1 Year Warranty
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16 GB LPDDR5 RAM,1 TB SSD,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1 Year Warranty
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1 Year Warranty
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16 GB RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1 Year Warranty

In [887]:
df1=df1.dropna(subset=["processor"])

In [888]:
df1.isna().sum()

brand         0
model         0
price         0
rating        0
processor     0
cores        15
ram           2
storage       4
display       0
graphics      6
os            0
warranty      3
dtype: int64

In [889]:
import re
import pandas as pd

def parse_cpu(name: str):
    """Extract brand, family, series, model, suffix from CPU string."""

    if pd.isna(name):
        return {
            "processor_brand": None,
            "processor_family": None,
            "processor_series": None,
            "processor_model": None,
            "processor_suffix": None,
        }

    s = str(name)
    s = re.sub(r"\s+", " ", s).strip()

    brand = family = series = model = suffix = None

    # ---------- BRAND ----------
    if re.search(r"\bIntel\b", s, re.IGNORECASE):
        brand = "Intel"
    elif re.search(r"\bAMD\b", s, re.IGNORECASE):
        brand = "AMD"
    elif re.search(r"\bApple\b", s, re.IGNORECASE):
        brand = "Apple"
    elif re.search(r"\bSnapdragon\b|\bQualcomm\b", s, re.IGNORECASE):
        brand = "Snapdragon"

    # ---------- FAMILY (brand-specific) ----------
    if brand == "Intel":
        fam_patterns = [
            (r"Core Ultra", "Core Ultra"),
            (r"\bCore\b", "Core"),
            (r"Pentium", "Pentium"),
            (r"Celeron", "Celeron"),
            (r"\bAtom\b", "Atom"),
            (r"Xeon", "Xeon"),
            # NEW: Intel N-series (N100, N200, etc.)
            (r"\bN\d{2,3}\b", "N-Series"),
        ]
    elif brand == "AMD":
        fam_patterns = [
            (r"Ryzen", "Ryzen"),
            (r"Athlon", "Athlon"),
            (r"EPYC", "EPYC"),
            (r"Threadripper", "Threadripper"),
            (r"A[\s-]?Series", "A-Series"),
            (r"\bFX\b", "FX"),
        ]
    elif brand == "Apple":
        fam_patterns = [
            (r"\bM[1-9]\b", "M-Series"),
        ]
    elif brand == "Snapdragon":
        fam_patterns = [
            (r"Snapdragon", "Snapdragon"),
        ]
    else:
        fam_patterns = []

    for pat, fam_val in fam_patterns:
        if re.search(pat, s, re.IGNORECASE):
            family = fam_val
            break

    # ---------- Series (brand-specific) ----------
    if brand == "Intel":
        m_series = re.search(
            r"(Core Ultra\s+[3579]|Core\s+i[3579]|Core\s+[3579]|Core\s+5|Core\s+7|Core\s+9|"
            r"Pentium|Celeron|Atom|Xeon)",
            s,
            re.IGNORECASE,
        )
        if m_series:
            series = m_series.group(0).title()

    elif brand == "AMD":
        m_ai = re.search(r"(Ryzen\s+AI\s+(?:3|5|7|9|MAX))", s, re.IGNORECASE)
        if m_ai:
            series = m_ai.group(0).title()
        else:
            m_series = re.search(r"(Ryzen\s+\d|Ryzen\s+[3-9])", s, re.IGNORECASE)
            if m_series:
                series = m_series.group(0).title()

    elif brand == "Apple":
        m_gen = re.search(r"\bM([1-9])\b", s, re.IGNORECASE)
        if m_gen:
            gen = m_gen.group(1)
            series = f"M{gen}"
            model = series

        m_model = re.search(r"\b(M[1-9])\s+(Pro|Max|Ultra)\b", s, re.IGNORECASE)
        if m_model:
            base = m_model.group(1).upper()
            suf = m_model.group(2).title()
            series = base
            model = f"{base} {suf}"
            suffix = suf

    elif brand == "Snapdragon":
        m_series = re.search(
            r"(Snapdragon\s+X|Snapdragon\s+8cx|Snapdragon\s+7c|Snapdragon)",
            s,
            re.IGNORECASE,
        )
        if m_series:
            series = m_series.group(0).title()

        after = re.split(r"Snapdragon(?:\s+X|\s+8cx|\s+7c)?", s, flags=re.IGNORECASE)
        if len(after) > 1:
            rest = after[1].strip(" -")
            if rest:
                model = rest

    # ---------- GENERIC MODEL DETECTION ----------
    if model is None:
        tokens = re.split(r"\s+", s)
        candidates = []
        for t in tokens:
            t_clean = t.strip(",()")
            if not re.search(r"\d", t_clean):
                continue
            if re.match(r"^\d+(st|nd|rd|th)$", t_clean.lower()):
                continue
            if re.match(r"^i[3579]$", t_clean.lower()):
                continue
            candidates.append(t_clean)

        if candidates:
            model = candidates[-1].upper()

    # ---------- Fill missing series from model ----------
    if model and series is None:
        if family:
            series = f"{family} {model}"
        else:
            series = model

    # ---------- Suffix from model ----------
    if model and suffix is None:
        m_suf = re.search(r"(\d+)([A-Za-z]+)$", model)
        if m_suf:
            suffix = m_suf.group(2).upper()

    return {
        "processor_brand": brand,
        "processor_family": family,
        "processor_series": series,
        "processor_model": model,
        "processor_suffix": suffix,
    }

In [890]:
parsed = df1["processor"].apply(parse_cpu).apply(pd.Series)
df1 = pd.concat([df1, parsed], axis=1)

In [891]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32 GB DDR5 RAM,1 TB SSD,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1 Year Warranty,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16 GB LPDDR5 RAM,1 TB SSD,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1 Year Warranty,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1 Year Warranty,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16 GB RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1 Year Warranty,Intel,Core,Core 5,120U,U

In [892]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   2
storage               4
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      2
processor_series      0
processor_model       3
processor_suffix    140
dtype: int64

In [893]:
df1["processor_family"].unique()

array(['Core Ultra', 'Core', 'Ryzen', 'Celeron', 'M-Series', 'Snapdragon',
       None, 'N-Series'], dtype=object)

In [894]:
df1["processor_series"].unique()

array(['Core Ultra 7', 'Core I5', 'Ryzen 3', 'Core I7', 'Core 5',
       'Core I3', 'Ryzen 5', 'Celeron', 'Ryzen 7', 'Core 7',
       'Core Ultra 9', 'Core Ultra 5', 'M5', 'Snapdragon X', 'Ryzen 9',
       'Ryzen Ai 5', 'Ryzen Ai 7', 'Core 3', '210H', 'Core I9',
       'Ryzen Ai 9', 'Ryzen Ai Max', 'M4', 'M3', 'N-Series N200',
       'N-Series N100'], dtype=object)

In [895]:
df1["processor_model"].unique()

array(['255HX', '13420H', '7320U', '1255U', '120U', '100U', '7430U',
       '14450HX', '7530U', 'N4020', '350', '1315U', '240H', '7330U',
       '7520U', '275HX', '155H', '13650HX', '14650HX', '125H', '340',
       'M5', '225H', '1355U', '1335U', '250', '1334U', '7435HS', '13620H',
       '5500U', '5825U', 'X1-26-100', '8940HX', '13450HX', '330', 'Plus',
       '185H', '9955HX', '210H', '13850HX', '1305U', '13700HX', '1115G4',
       'N4500', '155U', '256V', '7445H', '255H', '10100Y', '1235U',
       '14700HX', '14900HX', '7445HS', '7735HS', '285H', '7730U',
       '7535HS', '5625U', '226V', '1215U', '13500H', '255U', '365',
       'X1 26 100', '115U', '7235HS', '8840HX', '12450HX', '12450H',
       '5700U', '258V', '125U', '260', '5600U', '12650H', '8645HS', '270',
       'N305', None, '5600H', '228V', '370', '390', 'Plus X1P-42-100',
       '285HX', '12650HX', '13700H', 'N4020C', '8265U', '5300U', '150U',
       '8840H', '8840HS', 'HX370', 'Plus X1P-64-100', 'M4',
       'Elite X1E 78 100', '13900H', '8945HS', '11950H', '6600H', '266V',
       'M3', 'M4 Max', 'M4 Pro', '8840U', '12700H', '1340P', '12500H',
       '8945H', '7945HX', 'Plus X1P 42', 'Elite X1E-78-100', '1195G7',
       '8540U', '1135G7', 'Elite X1E-80-100', 'N200', 'Elite',
       'Plus X1E-80-100', 'N100', '8640U'], dtype=object)

In [896]:
df1["processor_suffix"].unique()

array(['HX', 'H', 'U', None, 'HS', 'V', 'Y', 'C', 'Max', 'Pro', 'P'],
      dtype=object)

In [897]:
df1[df1["processor_model"].isna()]

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
460,acer,Acer 15 Travel Lite TL15-53M Laptop (13th Gen ...,34990,53,13th Gen Intel Core i3,13th Gen Intel Core i3,16 GB RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",‎Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty,Intel,Core,Core I3,None,None
732,dell,Dell Latitude 3450 Laptop (13th Gen Core i5/ 1...,65900,48,13th Gen Intel Core i5,"10 Cores (2P + 8E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel Graphics,Windows 11 OS,1 Year Warranty,Intel,Core,Core I5,None,None
744,dell,Dell Latitude 3420 GD723ZG84 Laptop (11th Gen ...,55990,44,11th Gen Intel Core i5,11th Gen Intel Core i5,16 GB DDR4 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel Integrated Graphics,Ubuntu OS,3 Year Warranty,Intel,Core,Core I5,None,None

In [898]:
df1[df1["processor_family"].isna()]

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
108,msi,MSI Cyborg 15 B2RWEKG-217IN Gaming Laptop (Int...,95990,62,Intel 210H,"Octa Core (4P + 4E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",8 GB NVIDIA GeForce RTX 5050,Windows 11 OS,2 Year Warranty,Intel,None,210H,210H,H
230,lenovo,Lenovo IdeaPad Slim 5 ‎16IRH10R 83J10067IN Lap...,64990,53,Intel 210H,"Octa Core (4P + 4E), 12 Threads",16 GB LPDDR5x RAM,512 GB SSD,"15.6 inches, 1920 x 1200 pixels",Intel Integrated,Windows 11 OS,1 Year Warranty,Intel,None,210H,210H,H

In [899]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   2
storage               4
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      2
processor_series      0
processor_model       3
processor_suffix    140
dtype: int64

In [900]:
# Fill missing Intel families with a generic bucket
df1.loc[
    (df1["processor_brand"] == "Intel") & (df1["processor_family"].isna()),
    "processor_family"
] = "Core 5"

In [901]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32 GB DDR5 RAM,1 TB SSD,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1 Year Warranty,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16 GB LPDDR5 RAM,1 TB SSD,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1 Year Warranty,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1 Year Warranty,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16 GB RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1 Year Warranty,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1 Year Warranty,Intel,Core,Core 5,120U,U

In [902]:
df1["warranty"]=df1["warranty"].str.split(" ").str.get(0).astype(float)

In [903]:
df1.head()

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32 GB DDR5 RAM,1 TB SSD,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16 GB LPDDR5 RAM,1 TB SSD,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1.0,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16 GB LPDDR5 RAM,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1.0,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16 GB RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1.0,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16 GB DDR5 RAM,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1.0,Intel,Core,Core 5,120U,U

In [904]:
df1=df1.dropna(subset=["ram"])

In [905]:
df1["ram"]=df1["ram"].str.split(" ").str.get(0).astype(int)

In [906]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1 TB SSD,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1 TB SSD,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1.0,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512 GB SSD,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1.0,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512 GB SSD,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1.0,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512 GB SSD,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1.0,Intel,Core,Core 5,120U,U

In [907]:
df1=df1.dropna(subset=["storage"])

In [908]:
df1["storage"]=df1["storage"].str.split(" ").str.get(0).astype(int)

In [909]:
df1["storage"].unique()

array([  1, 512, 256,   2,  64, 128,   4,   6])

In [910]:
mask=df1["storage"].between(1,8,inclusive="both")

In [911]:
df1.loc[mask,"storage"]=df1.loc[mask,"storage"]*1024

In [912]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows 11 OS,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows 11 OS,1.0,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows 11 OS,1.0,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows 11 OS,1.0,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1.0,Intel,Core,Core 5,120U,U

In [913]:
df1["os"]=df1["os"].str.split(" ").str.get(0)

In [914]:
df1["os"].unique()

array(['Windows', 'Mac', 'Linux', 'Chrome', 'DOS', 'Ubuntu'], dtype=object)

In [915]:
df1["os"].isna().sum()

np.int64(0)

In [916]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U

In [917]:
display_size=df1["display"].str.split(" ").str.get(0)

In [918]:
df1.insert(8,"display_size",display_size)

In [919]:
df1.head()

,brand,model,price,rating,processor,cores,ram,storage,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,15.6,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,14,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,14,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U

In [920]:
display_width=df1["display"].str.split(" ").str.get(2).unique()

In [921]:
display_width=df1["display"].str.extract(r"(\d+\.?\d*)\s*x", expand=False)

In [922]:
df1.insert(8,"display_width",display_width)

In [923]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,2560,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,1920,15.6,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,1920,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,14,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,14,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U

In [924]:
display_height=df1["display"].str.extract(r"(\d+\.?\d*)\s*pixels", expand=False)

In [925]:
df1.insert(9,"display_height",display_height)

In [926]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,2560,1600,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U

In [927]:
df1["cores"].unique()

array(['20 Cores (8P + 12E), 20 Threads',
       'Octa Core (4P + 4E), 12 Threads', 'Quad Core, 8 Threads',
       '10 Cores (2P + 8E), 12 Threads', 'Hexa Core (2P + 4E), 8 Threads',
       'Hexa Core, 12 Threads', '10 Cores (6P + 4E), 16 Threads',
       'Dual Core, 2 Threads', 'Octa Core, 16 Threads',
       '24 Cores (8P + 16E), 24 Threads',
       '16 Cores (6P + 8E + 2LP-E), 22 Threads', '14 Cores (6P + 8E)',
       '16 Cores (8P + 8E), 24 Threads',
       '14 Cores (4P + 8E + 2LP-E), 18 Threads', '10 Cores (4P + 6E)',
       '14 Cores (4P + 8E + 2LP-E), 14 Threads', 'Octa Core',
       '16 Cores, 32 Threads', nan, '20 Cores (8P + 12E), 28 Threads',
       '5 Cores (1P + 4E), 6 Threads', 'Dual Core, 4 Threads',
       '12 Cores (2P + 8E + 2LP-E), 14 Threads',
       'Octa Core (4P + 4LP-E), 8 Threads',
       '16 Cores (6P + 8E + 2LP-E), 16 Threads',
       '24 Cores (8P + 16E), 32 Threads',
       '12 Cores (4P + 8E), 16 Threads', '12 Cores (2P + 8E + 2LP-E)',
       '10 Cores (4P + 6E), 20 Threads',
       'Octa Core (2P + 4E + 2LP-E), 10 Threads', '12 Cores, 24 Threads',
       'Octa Core (4P + 4E), 8 Threads', 'Octa Core, 8 Threads',
       '16 Cores', '13th Gen Intel Core i3',
       '12 Cores (4P + 8E), 24 Threads', 'Intel Core Ultra 5 228V',
       '14 Cores (6P + 8E), 20 Threads', '10 Cores',
       '12 Cores, 12 Threads', '11th Gen Intel Core i9 11950H',
       '11th Gen Intel Core i5', 'Intel Core Ultra 5 266V',
       'Octa Core (4P + 4E)', '14 Cores (10P + 4E)', '12 Cores (8P + 4E)',
       '12 Cores'], dtype=object)

In [928]:
df1["cores"].str.split(" ").str.get(0).unique()

array(['20', 'Octa', 'Quad', '10', 'Hexa', 'Dual', '24', '16', '14', nan,
       '5', '12', '13th', 'Intel', '11th'], dtype=object)

In [929]:
core_word_map = {
    "single": 1,
    "dual": 2,
    "triple": 3,
    "quad": 4,
    "penta": 5,
    "hexa": 6,
    "octa": 8,
    "deca": 10,
}

def extract_core_count(x):
    if pd.isna(x):
        return np.nan
    
    s = str(x).strip().lower()

    # 🚫 Ignore strings that look like CPU *names* not core configs
    # e.g. "13th Gen Intel Core i3", "Intel Core Ultra 5 228V"
    if ("intel core" in s or "core ultra" in s) and "cores" not in s:
        return np.nan

    # 1️⃣ Numeric pattern like "20 Cores", "10 Cores", "5 Cores (1P + 4E)"
    m_num = re.search(r"(\d+)\s+cores\b", s)
    if m_num:
        return int(m_num.group(1))

    # 2️⃣ Word-based pattern: "dual core", "quad core", "hexa core", "octa core"
    for word, value in core_word_map.items():
        # require "<word> core", not just the word alone
        if re.search(rf"\b{word}\s+core\b", s):
            return value

    # If nothing matches, it's probably not a real core config
    return np.nan

In [930]:
df1["core_count"] = df1["cores"].apply(extract_core_count)

In [931]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,2560,1600,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX,20.0
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H,8.0
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U,4.0
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U,10.0
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U,10.0

In [932]:
def extract_threads(x):
    if pd.isna(x):
        return np.nan

    s = str(x).lower().strip()

    # explicit thread count e.g., "20 Threads", "12 threads"
    m = re.search(r'(\d+)\s*threads?', s)
    if m:
        return int(m.group(1))

    # If no thread info present → NaN
    return np.nan

df1["threads_count"] = df1["cores"].apply(extract_threads)

In [933]:
def extract_core_breakdown(x):
    if pd.isna(x):
        return pd.Series(
            [np.nan, np.nan, np.nan],
            index=["p_cores", "e_cores", "lp_e_cores"]
        )
    
    s = str(x)

    # Find text inside parentheses: e.g. "(8P + 12E)" or "(6P + 8E + 2LP-E)"
    m = re.search(r"\(([^)]*)\)", s)
    if not m:
        return pd.Series(
            [np.nan, np.nan, np.nan],
            index=["p_cores", "e_cores", "lp_e_cores"]
        )

    inner = m.group(1)  # e.g. "8P + 12E", "6P + 8E + 2LP-E"

    # P-cores
    p_cores = np.nan
    m_p = re.search(r"(\d+)\s*P\b", inner, flags=re.IGNORECASE)
    if m_p:
        p_cores = int(m_p.group(1))

    # LP-E cores
    lp_e_cores = np.nan
    m_lp = re.search(r"(\d+)\s*LP-?E\b", inner, flags=re.IGNORECASE)
    if m_lp:
        lp_e_cores = int(m_lp.group(1))

    # E-cores: remove LP-E part first to avoid counting it as plain E
    inner_no_lp = re.sub(r"\d+\s*LP-?E\b", "", inner, flags=re.IGNORECASE)

    e_cores = np.nan
    m_e = re.search(r"(\d+)\s*E\b", inner_no_lp, flags=re.IGNORECASE)
    if m_e:
        e_cores = int(m_e.group(1))

    return pd.Series(
        [p_cores, e_cores, lp_e_cores],
        index=["p_cores", "e_cores", "lp_e_cores"]
    )

# Apply to your cores column
df1[["p_cores", "e_cores", "lp_e_cores"]] = df1["cores"].apply(extract_core_breakdown)

In [934]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,2560,1600,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX,20.0,20.0,8.0,12.0,NaN
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H,8.0,12.0,4.0,4.0,NaN
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U,4.0,8.0,NaN,NaN,NaN
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U,10.0,12.0,2.0,8.0,NaN
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U,10.0,12.0,2.0,8.0,NaN

In [935]:
df1.isnull().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         2
display_height        2
display_size          0
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      0
processor_series      0
processor_model       3
processor_suffix    136
core_count           20
threads_count        80
p_cores             313
e_cores             335
lp_e_cores          856
dtype: int64

In [936]:
df1[(df1["e_cores"].isna()) & (df1["p_cores"].notna())].shape[0]

22

In [937]:
df1.head()

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,2560,1600,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX,20.0,20.0,8.0,12.0,NaN
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H,8.0,12.0,4.0,4.0,NaN
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U,4.0,8.0,NaN,NaN,NaN
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U,10.0,12.0,2.0,8.0,NaN
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U,10.0,12.0,2.0,8.0,NaN

In [938]:
df1["graphics"].unique()

array(['8 GB NVIDIA® GeForce RTX 5060', 'Integrated Intel UHD Graphics',
       'AMD Radeon AMD', 'Integrated Intel Iris Xe Graphics',
       'Intel UHD Graphics', nan, 'AMD Radeon', 'AMD Radeon Graphics',
       '6 GB NVIDIA GeForce RTX 3050', '6 GB NVIDIA GeForce RTX 4050',
       'Intel Integrated', 'Intel Graphics',
       '8 GB NVIDIA GeForce RTX 5050', 'Intel Integrated UHD',
       'Intel HD Graphics', 'AMD Radeon Radeon Graphics',
       '24 GB NVIDIA GeForce RTX 5090', '16 GB NVIDIA GeForce RTX 5080',
       '8 GB NVIDIA GeForce RTX 4060', '8 GB NVIDIA GeForce RTX 5060',
       'Intel Integrated Arc', '10 Core GPU', 'Intel Arc GPU',
       'Intel Arc Graphics', '\u200eIntel Iris Xe Graphics',
       'Intel Iris Xe Graphics', 'Qualcomm Adreno GPU',
       '8 GB NVIDIA GeForce RTX 5070', 'AMD Radeon 610M',
       'AMD Radeon 820M', '4 GB NVIDIA RTX 500 Ada',
       '8 GB NVIDIA RTX 2000 Ada', 'Intel Integrated Intel® UHD Graphics',
       '6 GB NVIDIA RTX 1000 Ada', 'Integrated Intel Arc Graphics',
       'AMD Radeon 860M', '4 GB NVIDIA GeForce RTX 3050A',
       '6 GB NVIDIA RTX A1000', 'Intel Integrated UHD Graphics',
       'Intel Integrated Iris Xe', '4 GB NVIDIA GeForce RTX 2050',
       'Integrated Intel Graphics', 'Intel Integrated Intel UHD Graphics',
       '8 GB NVIDIA GEFORCE RTX 5050', 'Intel Arc 140T GPU',
       'Intel UHD Graphics 615', '\u200eIntel Graphics',
       '\u200eIntel UHD Graphics 600', '4 GB NVIDIA RTX A500',
       'Intel Integrated Intel', '4 GB NVIDIA GeForce RTX 3050',
       'Intel Integrated Graphics', 'Intel Integrated Intel Arc',
       'Intel integrated', '8 GB NVIDIA GeForce RTX 4070',
       'Intergrated AMD Radeon Graphics', 'Intel Arc 130V GPU (8GB)',
       'AMD Integrated', 'Intel Arc 140V GPU (8GB)',
       'AMD Radeon 880M Graphics', 'Integrated Intel Iris Graphics',
       'Qualcomm Adreno Adreno', 'NVIDIA RTX 3000 Ada Generation',
       'Intel Integrated Integrated', 'NVIDIA GeForce RTX 4050',
       '12 GB NVIDIA GeForce RTX 5070 Ti',
       '12 GB NVIDIA GEFORCE RTX 5070Ti',
       'Integrated AMD Radeon  Graphics', 'Intel Integrated Arc 140 V',
       '16 GB NVIDIA GEFORCE RTX 5080', '8 GB NVIDIA RTX 3000',
       '6 GB NVIDIA RTX 1000', 'Integrated AMD Radeon 660M Graphics',
       '12 GB NVIDIA GeForce RTX 5070Ti', 'Intel Integrated ARC Graphics',
       '4 GB NVIDIA Geforce RTX 3050', '4 GB NVIDIA RTX 500',
       'Integrated Intel Arc 140T GPU', '8 GB NVIDIA GEFORCE RTX 5060',
       'Integrated AMD Radeon Graphics', 'AMD Graphics',
       'Intel Integrated Intel HD', 'NVIDIA GeForce RTX Arc',
       '4 GB NVIDIA GeForce RTX 3050 A', 'AMD Radeon 610M Graphics',
       'Integrated Intel Arc Graphics 140V',
       'Intel Iris Xe Graphics comes', '\u200eIntel \u200eIntegrated',
       '4 GB AMD Radeon RX 6500M', '12 GB NVIDIA GeForce RTX 4080',
       'Qualcomm Adreno', 'AMD Radeon 680M', 'AMD Radeon 840M Graphics',
       'AMD Radeon 860M Graphics', '2 GB NVIDIA GeForce MX 230',
       '8 GB NVIDIA GEFORCE RTX 4070',
       'Integrated AMD Radeon 610M Graphics', 'Intel Arc 130V GPU',
       'Intel Arc 140V GPU', 'Intel Arc 140V GPU (16GB)',
       'Intel Arc Graphics 130V', 'Intel Arc Graphics 140V',
       'Integrated Qualcomm Adreno GPU', 'Apple 10 Core GPU',
       'Integrated Intel iris Xe Graphics',
       'Intergrated Intel Iris Xe Graphics', '\u200eIntel UHD Graphics',
       '8 GB NVIDIA GeForce RTX 3070',
       'Integrated Intel UHD Graphics 600', 'Intel Integrated Arc 140V',
       'Intel  Graphics', '16 GB NVIDIA GEFORCE RTX 4090',
       '12 GB NVIDIA GEFORCE RTX 4080', '10-Core GPU', '32 Core GPU',
       '20 Core GPU', '16 Core GPU', 'Apple 8 Core GPU',
       'Iris Xe Graphics', 'Intel UHD'], dtype=object)

In [939]:
import re
import pandas as pd

def parse_gpu(text: str):
    """
    Parse 'graphics' column into:
      - gpu_brand
      - gpu_series
      - gpu_model
      - gpu_vram  (int GB)
      - is_integrated (bool)
    """
    # Completely missing graphics info
    if pd.isna(text):
        return {
            "gpu_brand": None,
            "gpu_series": None,
            "gpu_model": None,
            "gpu_vram": None,
            "is_integrated": None,
        }

    s = str(text).strip()
    s_clean = re.sub(r"\s+", " ", s)
    s_lower = s_clean.lower()

    # ---------- VRAM ----------
    vram = None
    m_vram = re.search(r"(\d+)\s*gb", s_lower)
    if m_vram:
        vram = int(m_vram.group(1))

    # ---------- BRAND ----------
    brand = None
    if "nvidia" in s_lower:
        brand = "NVIDIA"
    elif "amd" in s_lower:
        brand = "AMD"
    elif "qualcomm" in s_lower or "adreno" in s_lower:
        brand = "Qualcomm"
    elif "intel" in s_lower:
        brand = "Intel"
    elif "iris xe" in s_lower:
        # sometimes only "Iris Xe Graphics" appears
        brand = "Intel"
    elif "mediatek" in s_lower:
        brand = "MediaTek"
    elif "mali-" in s_lower:
        brand = "ARM"
    elif "core gpu" in s_lower:
        # e.g. "10 Core GPU", "Apple 8 Core GPU"
        brand = "Apple"

    series = None
    model = None

    # strip VRAM prefix like "6 GB "
    body = re.sub(r"^\s*\d+\s*gb\s+", "", s_clean, flags=re.IGNORECASE)
    body_no_brand = body
    if brand:
        body_no_brand = re.sub(brand, "", body, flags=re.IGNORECASE).strip()
    b_low = body_no_brand.lower()

    # ---------- NVIDIA ----------
    if brand == "NVIDIA":
        if "geforce rtx" in b_low:
            series = "GeForce RTX"
        elif "geforce gtx" in b_low:
            series = "GeForce GTX"
        elif "geforce mx" in b_low:
            series = "GeForce MX"
        elif "geforce" in b_low:
            series = "GeForce"
        elif "rtx" in b_low:
            series = "RTX"

        # RTX/GTX/MX patterns
        m_model = (
            re.search(r"(rtx\s+[a-z]*\d+\w*)", b_low) or
            re.search(r"(gtx\s+[a-z]*\d+\w*)", b_low) or
            re.search(r"(mx\s+\d+\w*)", b_low)
        )
        if m_model:
            model = m_model.group(0).upper()
        else:
            m_fallback = re.search(r"(geforce\s+.+)", body_no_brand, flags=re.IGNORECASE)
            if m_fallback:
                model = m_fallback.group(0).strip()

    # ---------- AMD ----------
    elif brand == "AMD":
        m_rad = re.search(r"(radeon\s+.+)", body_no_brand, flags=re.IGNORECASE)
        if m_rad:
            rad_part = m_rad.group(1).strip()
            series = "Radeon"
            after = re.sub(r"radeon", "", rad_part, flags=re.IGNORECASE).strip()
            model = after if after else "Radeon"
        elif "radeon" in b_low:
            series = "Radeon"
            model = "Radeon"
        else:
            if "graphics" in b_low or "integrated" in b_low:
                series = "Graphics"
                model = "AMD Graphics"

    # ---------- INTEL ----------
    elif brand == "Intel":
        b_low = body_no_brand.lower()
        if "iris xe" in b_low:
            series = "Iris Xe"
            model = "Iris Xe Graphics"
        elif "uhd" in b_low:
            series = "UHD"
            m_uhd = re.search(r"uhd(?:\s+graphics)?\s*(\d+)?", b_low)
            if m_uhd:
                if m_uhd.group(1):
                    model = f"UHD {m_uhd.group(1)}"
                else:
                    model = "UHD Graphics"
        elif "hd graphics" in b_low or "intel hd" in b_low:
            series = "HD"
            model = "HD Graphics"
        elif "arc" in b_low:
            series = "Arc"
            m_arc = re.search(r"(arc\s+.+)", body_no_brand, flags=re.IGNORECASE)
            model = m_arc.group(1).strip() if m_arc else "Arc Graphics"
        else:
            if "graphics" in b_low or "integrated" in b_low or "hd" in b_low:
                series = "Integrated Graphics"
                model = "Intel Integrated Graphics"

    # ---------- Qualcomm / Adreno ----------
    elif brand == "Qualcomm":
        series = "Adreno"
        m_adr = re.search(r"(adreno\s+\w+)", b_low, flags=re.IGNORECASE)
        model = m_adr.group(1).title() if m_adr else "Adreno GPU"

    # ---------- MediaTek / ARM ----------
    elif brand in ("MediaTek", "ARM"):
        m_mali = re.search(r"(mali-\w+)", s_lower)
        if m_mali:
            series = "Mali"
            model = m_mali.group(0).upper()
        else:
            series = "Integrated Graphics"
            model = s_clean

    # ---------- Apple ----------
    elif brand == "Apple":
        series = "Apple GPU"
        model = s_clean

    # ---------- Fallback for unknown brand ----------
    else:
        if "integrated" in s_lower and "graphics" in s_lower:
            series = "Integrated Graphics"
            model = s_clean

    # ---------- is_integrated ----------
    is_integrated = None
    if "dedicated" in s_lower:
        is_integrated = False
    elif "integrated" in s_lower:
        is_integrated = True
    elif brand == "NVIDIA":
        # NVIDIA is almost always discrete in your dataset
        is_integrated = False
    elif brand in ("Intel", "AMD", "Qualcomm", "Apple", "MediaTek", "ARM"):
        # if no VRAM mentioned, treat as integrated; if VRAM mentioned, treat as discrete
        is_integrated = (vram is None)

    return {
        "gpu_brand": brand,
        "gpu_series": series,
        "gpu_model": model,
        "gpu_vram": vram,
        "is_integrated": is_integrated,
    }

# ---- Apply on your df1 ----
gpu_parsed = df1["graphics"].apply(parse_gpu).apply(pd.Series)
df1[["gpu_brand", "gpu_series", "gpu_model", "gpu_vram", "is_integrated"]] = \
    gpu_parsed[["gpu_brand", "gpu_series", "gpu_model", "gpu_vram", "is_integrated"]]

# If you want to verify:
# df1[df1["graphics"].notna() & df1["is_integrated"].isna()].shape

In [940]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,2560,1600,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX,20.0,20.0,8.0,12.0,NaN,NVIDIA,GeForce RTX,RTX 5060,8.0,False
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H,8.0,12.0,4.0,4.0,NaN,Intel,UHD,UHD Graphics,NaN,True
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U,4.0,8.0,NaN,NaN,NaN,AMD,Radeon,Radeon,NaN,True
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U,10.0,12.0,2.0,8.0,NaN,Intel,Iris Xe,Iris Xe Graphics,NaN,True
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U,10.0,12.0,2.0,8.0,NaN,Intel,UHD,UHD Graphics,NaN,True

In [941]:
def parse_model_smart(name: str):
    """
    Extract ONLY:
    - series_name
    - device_type
    with special handling for:
      * HP 15s-/14s-/15- style
      * HP 240R G9 / 250R G9
      * Chromebooks (Asus / Acer / Lenovo)
      * Asus Gaming V16 ...
      * Acer Aspire Lite ...
      * Simple code-only models (Walker NU15A1, Dell DC15255)
    """
    if pd.isna(name):
        return {
            "series_name": None,
            "device_type": None
        }

    s = str(name).strip()
    s_clean = re.sub(r"\s+", " ", s)
    s_lower = s_clean.lower()

    # Only use part before "(" (after that are specs)
    main_part = s_clean.split("(", 1)[0].strip()
    tokens = main_part.split()

    if not tokens:
        return {
            "series_name": None,
            "device_type": None
        }

    brand = tokens[0]

    # ---------------- DEVICE TYPE ----------------
    device_type = "General"

    gaming_keywords = ["gaming", "rog", "tuf", "legion", "omen", "victus",
                       "predator", "alienware", "zephyrus"]

    business_keywords = ["thinkpad", "latitude", "probook", "elitebook",
                         "thinkbook", "vostro", "240r g9", "250r g9"]

    convertible_keywords = ["2-in-1", "2 in 1", "convertible", "flip", "x360", "yoga"]

    thin_light_keywords = ["slim", "air", "swift", "vivobook", "go", "gram"]

    if any(k in s_lower for k in gaming_keywords):
        device_type = "Gaming"
    elif any(k in s_lower for k in convertible_keywords):
        device_type = "Convertible"
    elif any(k in s_lower for k in business_keywords):
        device_type = "Business"
    elif any(k in s_lower for k in thin_light_keywords):
        device_type = "Thin & Light"

    # ---------------- SERIES NAME ----------------
    STOP_WORDS = {"laptop", "notebook", "chromebook"}  # note: "gaming" handled via special case

    def is_year_token(t: str) -> bool:
        return bool(re.fullmatch(r"20\d\d", t))

    def is_heavy_code(t: str) -> bool:
        """Very long codey tokens we don't want in series (A9UK7PT##ACJ, etc.)."""
        t_clean = re.sub(r"[^A-Za-z0-9]", "", t)
        return len(t_clean) >= 7 and re.search(r"[A-Za-z]", t_clean) and re.search(r"\d", t_clean)

    series_tokens = []

    # ------------ Brand-specific rules ------------

    # 1) HP special patterns
    if brand == "HP" and len(tokens) >= 2:
        t1 = re.sub(r"[,:;()]+$", "", tokens[1])

        # a) HP 15-fd0468TU / 15s-fc0156AU / 14s-dq3141TU etc.
        m_hp_hyphen = re.match(r"^(\d+s?)\-", t1, re.IGNORECASE)
        if m_hp_hyphen:
            series_tokens = [m_hp_hyphen.group(1)]  # '15', '15s', '14s'
            return {
                "series_name": " ".join(series_tokens),
                "device_type": device_type
            }

        # b) HP 15 2025 → want "15" only (avoid year)
        if len(tokens) >= 3 and re.fullmatch(r"\d{2,3}", tokens[1]) and is_year_token(tokens[2]):
            series_tokens = [tokens[1]]
            return {
                "series_name": " ".join(series_tokens),
                "device_type": device_type
            }

        # c) HP 240R G9 A9UK7PT##ACJ Laptop → "240R G9"
        if len(tokens) >= 3 and re.match(r"^\d+[A-Za-z]$", tokens[1]) and re.match(r"^G\d+$", tokens[2], re.IGNORECASE):
            series_tokens = [tokens[1], tokens[2]]
            return {
                "series_name": " ".join(series_tokens),
                "device_type": device_type
            }

    # 2) Chromebooks: Asus/Acer/Lenovo Chromebook CX1500...
    if brand in ("Asus", "Acer", "Lenovo") and len(tokens) >= 2 and tokens[1].lower() == "chromebook":
        # e.g., "Asus Chromebook CX1500FKA-E80077 Laptop"
        if len(tokens) >= 3 and not is_heavy_code(tokens[2]) and tokens[2].lower() not in STOP_WORDS:
            series_tokens = [tokens[1], tokens[2]]
        else:
            series_tokens = [tokens[1]]
        return {
            "series_name": " ".join(series_tokens),
            "device_type": device_type
        }

    # 3) Asus Gaming V16 ...
    if brand == "Asus" and len(tokens) >= 3 and tokens[1].lower() == "gaming" and tokens[2].lower().startswith("v"):
        # "Asus Gaming V16 2025 V3607VH-RP038WS Laptop..."
        series_tokens = [tokens[1], tokens[2]]  # "Gaming V16"
        return {
            "series_name": " ".join(series_tokens),
            "device_type": device_type
        }

    # 4) Acer Aspire Lite ...
    #    "Acer AL15-52H Aspire Lite 15 Laptop..."
    if brand == "Acer":
        for i, t in enumerate(tokens):
            if t.lower() == "aspire":
                # Take from "Aspire" up to "Laptop" or other stop word
                end = len(tokens)
                for j in range(i, len(tokens)):
                    if tokens[j].lower() in STOP_WORDS:
                        end = j
                        break
                series_tokens = tokens[i:end]  # e.g. ["Aspire", "Lite", "15"]
                return {
                    "series_name": " ".join(series_tokens),
                    "device_type": device_type
                }

    # ------------ Generic fallback ------------

    # Collect tokens after brand until a STOP_WORD or heavy code
    for i, t in enumerate(tokens[1:], start=1):
        t_clean = re.sub(r"[,:;()]+$", "", t)
        t_low = t_clean.lower()

        if t_low in STOP_WORDS:
            break

        if is_heavy_code(t_clean):
            break

        series_tokens.append(t_clean)

    # If still nothing, fall back to just the second token (like DC15255, NU15A1)
    if not series_tokens and len(tokens) >= 2:
        series_tokens = [re.sub(r"[,:;()]+$", "", tokens[1])]

    series_name = " ".join(series_tokens) if series_tokens else None

    return {
        "series_name": series_name,
        "device_type": device_type
    }

# ---- APPLY TO df1 ----
model_parsed = df1["model"].apply(parse_model_smart).apply(pd.Series)

df1[["series_name", "device_type"]] = model_parsed[["series_name", "device_type"]]

In [942]:
df1.head(5)

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",32,1024,2560,1600,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX,20.0,20.0,8.0,12.0,NaN,NVIDIA,GeForce RTX,RTX 5060,8.0,False,Legion Pro 5,Gaming
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,"Octa Core (4P + 4E), 12 Threads",16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Windows,1.0,Intel,Core,Core I5,13420H,H,8.0,12.0,4.0,4.0,NaN,Intel,UHD,UHD Graphics,NaN,True,IdeaPad Slim 3,Thin & Light
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,Windows,1.0,AMD,Ryzen,Ryzen 3,7320U,U,4.0,8.0,NaN,NaN,NaN,AMD,Radeon,Radeon,NaN,True,Vivobook Go 15,Thin & Light
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Windows,1.0,Intel,Core,Core I7,1255U,U,10.0,12.0,2.0,8.0,NaN,Intel,Iris Xe,Iris Xe Graphics,NaN,True,V14 G3,General
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,"10 Cores (2P + 8E), 12 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows,1.0,Intel,Core,Core 5,120U,U,10.0,12.0,2.0,8.0,NaN,Intel,UHD,UHD Graphics,NaN,True,DC 14250,General

In [943]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         2
display_height        2
display_size          0
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      0
processor_series      0
processor_model       3
processor_suffix    136
core_count           20
threads_count        80
p_cores             313
e_cores             335
lp_e_cores          856
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
dtype: int64

In [947]:
df1[df1["processor_model"].isna()]

Empty DataFrame
Columns: [brand, model, price, rating, processor, cores, ram, storage, display_width, display_height, display_size, display, graphics, os, warranty, processor_brand, processor_family, processor_series, processor_model, processor_suffix, core_count, threads_count, p_cores, e_cores, lp_e_cores, gpu_brand, gpu_series, gpu_model, gpu_vram, is_integrated, series_name, device_type]
Index: []

In [946]:
import numpy as np

# 1) Acer 15 Travel Lite TL15-53M  – assumed Intel Core i3-1315U
mask_acer_tl15 = df1["model"].str.contains("Travel Lite TL15-53M", na=False)

df1.loc[mask_acer_tl15, [
    "processor_model",
    "processor_suffix",
    "core_count",
    "threads_count",
    "p_cores",
    "e_cores",
    "lp_e_cores"
]] = [
    "1315U",   # processor_model
    "U",       # processor_suffix
    6,         # core_count  (2P + 4E)
    8,         # threads_count
    2,         # p_cores
    4,         # e_cores
    0          # lp_e_cores (none)
]


# 2) Dell Latitude 3450 – Intel Core i5-1335U
mask_lat_3450 = df1["model"].str.contains("Latitude 3450", na=False)

df1.loc[mask_lat_3450, [
    "processor_model",
    "processor_suffix",
    "core_count",
    "threads_count",
    "p_cores",
    "e_cores",
    "lp_e_cores"
]] = [
    "1335U",   # processor_model
    "U",       # processor_suffix
    10,        # core_count  (2P + 8E)
    12,        # threads_count
    2,         # p_cores
    8,         # e_cores
    0          # lp_e_cores
]


# 3) Dell Latitude 3420 GD723ZG84 – Intel Core i5-1135G7
mask_lat_3420 = df1["model"].str.contains("Latitude 3420", na=False)

df1.loc[mask_lat_3420, [
    "processor_model",
    "processor_suffix",
    "core_count",
    "threads_count",
    "p_cores",
    "e_cores",
    "lp_e_cores"
]] = [
    "1135G7",  # processor_model
    "G7",      # processor_suffix
    4,         # core_count  (all P-cores, 11th Gen)
    8,         # threads_count
    4,         # p_cores
    0,         # e_cores
    0          # lp_e_cores
]

In [948]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         2
display_height        2
display_size          0
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      0
processor_series      0
processor_model       0
processor_suffix    133
core_count           18
threads_count        78
p_cores             311
e_cores             333
lp_e_cores          852
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
dtype: int64

In [949]:
df1[df1["display_width"].isna()]

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type
762,acer,Acer Swift 14 AI SF14-51 NX.J2HSI.001Laptop (I...,82500,62,Intel Core Ultra 7 258V,"Octa Core (4P + 4E), 8 Threads",16,1024,NaN,NaN,14,14 inches,Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 7,258V,V,8.0,8.0,4.0,4.0,NaN,Intel,Arc,Arc Graphics,NaN,True,Swift 14 AI SF14-51,Thin & Light
763,acer,Acer Swift 14 AI SF14-51 NX.J2HSI.002 Laptop (...,89999,56,Intel Core Ultra 5 266V,Intel Core Ultra 5 266V,16,512,NaN,NaN,14,14 inches,Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 5,266V,V,NaN,NaN,NaN,NaN,NaN,Intel,Arc,Arc Graphics,NaN,True,Swift 14 AI SF14-51,Thin & Light

In [950]:
# Mask for both Acer Swift 14 AI SF14-51 laptops
mask_swift14 = df1["model"].str.contains("Swift 14 AI SF14-51", na=False)

df1.loc[mask_swift14, ["display_width", "display_height"]] = [1920, 1200]

In [951]:
df1.loc[mask_swift14, ["model", "display_width", "display_height", "display_size"]]

,model,display_width,display_height,display_size
762,Acer Swift 14 AI SF14-51 NX.J2HSI.001Laptop (I...,1920,1200,14
763,Acer Swift 14 AI SF14-51 NX.J2HSI.002 Laptop (...,1920,1200,14

In [952]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         0
display_height        0
display_size          0
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      0
processor_series      0
processor_model       0
processor_suffix    133
core_count           18
threads_count        78
p_cores             311
e_cores             333
lp_e_cores          852
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
dtype: int64

In [953]:
df1[df1["cores"].isna()]

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type
54,lenovo,Lenovo IdeaPad Slim 5 14AKP10 83HX008XIN Lapto...,69990,48,AMD Ryzen AI 5 AI 5 330,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",AMD Radeon 820M,Windows,1.0,AMD,Ryzen,Ryzen Ai 5,330,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,820M,NaN,True,IdeaPad Slim 5,Thin & Light
73,lenovo,Lenovo IdeaPad Slim 3 83N3002QIN Laptop (Qualc...,61590,39,Qualcomm Snapdragon X X1-26-100,NaN,16,512,1920,1200,15.3,"15.3 inches, 1920 x 1200 pixels",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,X1-26-100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,IdeaPad Slim 3,Thin & Light
130,asus,Asus TUF Gaming A16 2025 FA607NUG-RL191WS Gami...,97990,65,AMD Ryzen 7 7445HS,NaN,32,1024,1920,1200,16,"16 inches, 1920 x 1200 pixels",6 GB NVIDIA GeForce RTX 4050,Windows,1.0,AMD,Ryzen,Ryzen 7,7445HS,HS,NaN,NaN,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 4050,6.0,False,TUF Gaming A16 2025,Gaming
172,asus,Asus VivoBook S14 M3407KA-SF044WS Laptop (AMD ...,70990,48,AMD Ryzen AI 5 330,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",AMD Radeon Graphics,Windows,1.0,AMD,Ryzen,Ryzen Ai 5,330,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,Graphics,NaN,True,VivoBook S14,Thin & Light
194,asus,Asus VivoBook 14 M1407KA-LY132WS Laptop (AMD R...,61990,47,AMD Ryzen AI 5 330,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",AMD Radeon Graphics,Windows,1.0,AMD,Ryzen,Ryzen Ai 5,330,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,Graphics,NaN,True,VivoBook 14,Thin & Light
208,dell,Dell 14 Plus ODB1425550701RINU1 AI Laptop (AMD...,68490,43,AMD Ryzen AI 5 340,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",AMD Radeon,Windows,1.0,AMD,Ryzen,Ryzen Ai 5,340,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,Radeon,NaN,True,14 Plus,General
234,asus,Asus Vivobook S16 2025 S3607QA-SH074WS Laptop ...,72990,44,Qualcomm Snapdragon X X1 26 100,NaN,16,512,1920,1200,16,"16 inches, 1920 x 1200 pixels",Qualcomm Adreno Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,X1 26 100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Adreno,NaN,True,Vivobook S16 2025,Thin & Light
241,asus,Asus TUF Gaming A16 FA607NUG-RL189WS Gaming La...,89990,64,AMD Ryzen 7 7445HS,NaN,16,1024,1920,1200,16,"16 inches, 1920 x 1200 pixels",6 GB NVIDIA GeForce RTX 4050,Windows,1.0,AMD,Ryzen,Ryzen 7,7445HS,HS,NaN,NaN,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 4050,6.0,False,TUF Gaming A16,Gaming
279,asus,Asus TUF Gaming A15 FA506NCG-HN251WS Laptop (A...,75990,59,7th Gen AMD Ryzen 7 7445HS,NaN,16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",4 GB NVIDIA GeForce RTX 3050,Windows,1.0,AMD,Ryzen,Ryzen 7,7445HS,HS,NaN,NaN,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 3050,4.0,False,TUF Gaming A15,Gaming
309,asus,Asus Vivobook 14 X1407QA-LY038WS Laptop (Qualc...,54990,44,Qualcomm Snapdragon X X1 26 100,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",Qualcomm Adreno Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,X1 26 100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Adreno,NaN,True,Vivobook 14,Thin & Light
443,msi,MSI Venture A15 AI A2HMG-007IN Laptop (AMD Ryz...,79990,47,AMD Ryzen 7 260,NaN,16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon Graphics,Windows,1.0,AMD,Ryzen,Ryzen 7,260,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,Graphics,NaN,True,Venture A15 AI,General
516,lenovo,Lenovo IdeaPad Slim 5 14Q8X9 83HL003NIN Laptop...,79990,38,Qualcomm Snapdragon X Plus X1P-42-100,NaN,16,1024,1920,1200,14,"14 inches, 1920 x 1200 pixels",Qualcomm Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-42-100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno GPU,NaN,True,IdeaPad Slim 5 14Q8X9,Thin & Light
761,acer,Acer Swift Go 14 SFG14-01 NX.KYXSI.001 AI Lapt...,77990,46,Qualcomm Snapdragon X Plus,NaN,16,512,2560,1440,14.5,"14.5 inches, 2560 x 1440 pixels, Touch Screen",Qualcomm Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno GPU,NaN,True,Swift Go 14,Thin & Light
826,lenovo,Lenovo Ideapad Slim 5x Gen 9 14Q8X9 83HL0035IN...,71899,39,Qualcomm Snapdragon X Plus X1P-42-100,NaN,16,1024,1920,1200,14,"14 inches, 1920 x 1200 pixels",Qualcomm Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-42-100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno GPU,NaN,True,Ideapad Slim 5x Gen 9 14Q8X9,Thin & Light
865,asus,Asus Vivobook S 15 OLED S5507QA-MA551WS Laptop...,69994,48,Qualcomm Snapdragon X Plus X1P 42,NaN,16,1024,2880,1620,15.6,"15.6 inches, 2880 x 1620 pixels",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P 42,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Vivobook S 15 OLED,Thin & Light

In [954]:
cpu_specs = {
    # AMD Ryzen AI Series
    "Ryzen AI 5 330": {"core_count": 6, "threads": 12, "p": 0, "e": 0, "lp": 0},
    "Ryzen AI 5 340": {"core_count": 6, "threads": 12, "p": 0, "e": 0, "lp": 0},
    "Ryzen 7 260": {"core_count": 8, "threads": 16, "p": 0, "e": 0, "lp": 0},
    "Ryzen 7 7445HS": {"core_count": 8, "threads": 16, "p": 0, "e": 0, "lp": 0},

    # Snapdragon X Series
    "Snapdragon X1-26-100": {"core_count": 10, "threads": 10, "p": 0, "e": 0, "lp": 0},
    "Snapdragon X Plus": {"core_count": 10, "threads": 10, "p": 0, "e": 0, "lp": 0},
    "Snapdragon X X1 26 100": {"core_count": 10, "threads": 10, "p": 0, "e": 0, "lp": 0},
    "Snapdragon X Plus X1P-42-100": {"core_count": 10, "threads": 10, "p": 0, "e": 0, "lp": 0},

    # Intel example (can extend)
    "Core Ultra 7 258V": {"core_count": 8, "threads": 8, "p": 4, "e": 4, "lp": 0},
    "Core Ultra 5 266V": {"core_count": 8, "threads": 8, "p": 4, "e": 4, "lp": 0},
}

In [955]:
def fill_cpu_specs(row):
    model = row["processor_model"]

    if pd.isna(model):
        return row  # no change

    key = model.strip()

    if key in cpu_specs:
        spec = cpu_specs[key]
        row["core_count"] = spec["core_count"]
        row["threads_count"] = spec["threads"]
        row["p_cores"] = spec["p"]
        row["e_cores"] = spec["e"]
        row["lp_e_cores"] = spec["lp"]

    return row

df1 = df1.apply(fill_cpu_specs, axis=1)

In [956]:
df1[df1["core_count"].isna()]["processor"].unique()

array(['AMD Ryzen AI 5 AI 5 330', 'Qualcomm Snapdragon X X1-26-100',
       'AMD Ryzen 7 7445HS', 'AMD Ryzen AI 5 330', 'AMD Ryzen AI 5 340',
       'Qualcomm Snapdragon X X1 26 100', '7th Gen AMD Ryzen 7 7445HS',
       'AMD Ryzen 7 260', 'Qualcomm Snapdragon X Plus X1P-42-100',
       'Intel Core Ultra 5 228V', '11th Gen Intel Core i9 11950H',
       'Qualcomm Snapdragon X Plus', 'Intel Core Ultra 5 266V',
       'Qualcomm Snapdragon X Plus X1P 42'], dtype=object)

In [957]:
df1[df1["core_count"].isna()]["processor_model"].unique()

array(['330', 'X1-26-100', '7445HS', '340', 'X1 26 100', '260',
       'Plus X1P-42-100', '228V', '11950H', 'Plus', '266V', 'Plus X1P 42'],
      dtype=object)

In [958]:
df1[df1["core_count"].isna()]["processor_model"].unique()

array(['330', 'X1-26-100', '7445HS', '340', 'X1 26 100', '260',
       'Plus X1P-42-100', '228V', '11950H', 'Plus', '266V', 'Plus X1P 42'],
      dtype=object)

In [959]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         0
display_height        0
display_size          0
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      0
processor_series      0
processor_model       0
processor_suffix    133
core_count           18
threads_count        78
p_cores             311
e_cores             333
lp_e_cores          852
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
dtype: int64

In [960]:
df1[df1["core_count"].isna()]

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type
54,lenovo,Lenovo IdeaPad Slim 5 14AKP10 83HX008XIN Lapto...,69990,48,AMD Ryzen AI 5 AI 5 330,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",AMD Radeon 820M,Windows,1.0,AMD,Ryzen,Ryzen Ai 5,330,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,820M,NaN,True,IdeaPad Slim 5,Thin & Light
73,lenovo,Lenovo IdeaPad Slim 3 83N3002QIN Laptop (Qualc...,61590,39,Qualcomm Snapdragon X X1-26-100,NaN,16,512,1920,1200,15.3,"15.3 inches, 1920 x 1200 pixels",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,X1-26-100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,IdeaPad Slim 3,Thin & Light
130,asus,Asus TUF Gaming A16 2025 FA607NUG-RL191WS Gami...,97990,65,AMD Ryzen 7 7445HS,NaN,32,1024,1920,1200,16,"16 inches, 1920 x 1200 pixels",6 GB NVIDIA GeForce RTX 4050,Windows,1.0,AMD,Ryzen,Ryzen 7,7445HS,HS,NaN,NaN,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 4050,6.0,False,TUF Gaming A16 2025,Gaming
172,asus,Asus VivoBook S14 M3407KA-SF044WS Laptop (AMD ...,70990,48,AMD Ryzen AI 5 330,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",AMD Radeon Graphics,Windows,1.0,AMD,Ryzen,Ryzen Ai 5,330,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,Graphics,NaN,True,VivoBook S14,Thin & Light
194,asus,Asus VivoBook 14 M1407KA-LY132WS Laptop (AMD R...,61990,47,AMD Ryzen AI 5 330,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",AMD Radeon Graphics,Windows,1.0,AMD,Ryzen,Ryzen Ai 5,330,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,Graphics,NaN,True,VivoBook 14,Thin & Light
208,dell,Dell 14 Plus ODB1425550701RINU1 AI Laptop (AMD...,68490,43,AMD Ryzen AI 5 340,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",AMD Radeon,Windows,1.0,AMD,Ryzen,Ryzen Ai 5,340,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,Radeon,NaN,True,14 Plus,General
234,asus,Asus Vivobook S16 2025 S3607QA-SH074WS Laptop ...,72990,44,Qualcomm Snapdragon X X1 26 100,NaN,16,512,1920,1200,16,"16 inches, 1920 x 1200 pixels",Qualcomm Adreno Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,X1 26 100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Adreno,NaN,True,Vivobook S16 2025,Thin & Light
241,asus,Asus TUF Gaming A16 FA607NUG-RL189WS Gaming La...,89990,64,AMD Ryzen 7 7445HS,NaN,16,1024,1920,1200,16,"16 inches, 1920 x 1200 pixels",6 GB NVIDIA GeForce RTX 4050,Windows,1.0,AMD,Ryzen,Ryzen 7,7445HS,HS,NaN,NaN,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 4050,6.0,False,TUF Gaming A16,Gaming
279,asus,Asus TUF Gaming A15 FA506NCG-HN251WS Laptop (A...,75990,59,7th Gen AMD Ryzen 7 7445HS,NaN,16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",4 GB NVIDIA GeForce RTX 3050,Windows,1.0,AMD,Ryzen,Ryzen 7,7445HS,HS,NaN,NaN,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 3050,4.0,False,TUF Gaming A15,Gaming
309,asus,Asus Vivobook 14 X1407QA-LY038WS Laptop (Qualc...,54990,44,Qualcomm Snapdragon X X1 26 100,NaN,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",Qualcomm Adreno Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,X1 26 100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Adreno,NaN,True,Vivobook 14,Thin & Light
443,msi,MSI Venture A15 AI A2HMG-007IN Laptop (AMD Ryz...,79990,47,AMD Ryzen 7 260,NaN,16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon Graphics,Windows,1.0,AMD,Ryzen,Ryzen 7,260,None,NaN,NaN,NaN,NaN,NaN,AMD,Radeon,Graphics,NaN,True,Venture A15 AI,General
516,lenovo,Lenovo IdeaPad Slim 5 14Q8X9 83HL003NIN Laptop...,79990,38,Qualcomm Snapdragon X Plus X1P-42-100,NaN,16,1024,1920,1200,14,"14 inches, 1920 x 1200 pixels",Qualcomm Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-42-100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno GPU,NaN,True,IdeaPad Slim 5 14Q8X9,Thin & Light
522,lenovo,Lenovo Yoga Slim 7 14ILL10 83JX001LIN Laptop (...,112990,54,Intel Core Ultra 5 228V,Intel Core Ultra 5 228V,32,1024,1920,1200,14,"14 inches, 1920 x 1200 pixels",Integrated Intel Arc Graphics,Windows,1.0,Intel,Core Ultra,Core Ultra 5,228V,V,NaN,NaN,NaN,NaN,NaN,Intel,Arc,Arc Graphics,NaN,True,Yoga Slim 7,Convertible
710,lenovo,Lenovo ThinkPad T15g 20YSS01J00 Laptop (11th G...,122000,63,11th Gen Intel Core i9 11950H,11th Gen Intel Core i9 11950H,16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",8 GB NVIDIA GeForce RTX 3070,Windows,1.0,Intel,Core,Core I9,11950H,H,NaN,NaN,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 3070,8.0,False,ThinkPad T15g,Business
761,acer,Acer Swift Go 14 SFG14-01 NX.KYXSI.001 AI Lapt...,77990,46,Qualcomm Snapdragon X Plus,NaN,16,512,2560,1440,14.5,"14.5 inches, 2560 x 1440 pixels, Touch Screen",Qualcomm Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno GPU,NaN,True,Swift Go 14,Thin & Light
763,acer,Acer Swift 14 AI SF14-51 NX.J2HSI.002 Laptop (...,89999,56,Intel Core Ultra 5 266V,Intel Core Ultra 5 266V,16,512,1920,1200,14,14 inches,Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 5,266V,V,NaN,NaN,NaN,NaN,NaN,Intel,Arc,Arc Graphics,NaN,True,Swift 14 AI SF14-51,Thin & Light
826,lenovo,Lenovo Ideapad Slim 5x Gen 9 14Q8X9 83HL0035IN...,71899,39,Qualcomm Snapdragon X Plus X1P-42-100,NaN,16,1024,1920,1200,14,"14 inches, 1920 x 1200 pixels",Qualcomm Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-42-100,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno GPU,NaN,True,Ideapad Slim 5x Gen 9 14Q8X9,Thin & Light
865,asus,Asus Vivobook S 15 OLED S5507QA-MA551WS Laptop...,69994,48,Qualcomm Snapdragon X Plus X1P 42,NaN,16,1024,2880,1620,15.6,"15.6 inches, 2880 x 1620 pixels",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P 42,None,NaN,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Vivobook S 15 OLED,Thin & Light

In [961]:
cpu_lookup = {
    "330":              {"core": 8,  "threads": 16, "p": 0, "e": 8, "lp": 0},
    "340":              {"core": 8,  "threads": 16, "p": 0, "e": 8, "lp": 0},
    "7445HS":           {"core": 8,  "threads": 16, "p": 8, "e": 0, "lp": 0},
    "260":              {"core": 8,  "threads": 16, "p": 0, "e": 8, "lp": 0},

    "X1-26-100":        {"core": 10, "threads": 10, "p": 10, "e": 0, "lp": 0},
    "X1 26 100":        {"core": 10, "threads": 10, "p": 10, "e": 0, "lp": 0},
    "Plus X1P-42-100":  {"core": 10, "threads": 10, "p": 10, "e": 0, "lp": 0},
    "Plus X1P 42":      {"core": 10, "threads": 10, "p": 10, "e": 0, "lp": 0},
    "Plus":             {"core": 10, "threads": 10, "p": 10, "e": 0, "lp": 0},

    "228V":             {"core": 12, "threads": 16, "p": 4, "e": 8, "lp": 2},
    "266V":             {"core": 12, "threads": 14, "p": 2, "e": 8, "lp": 2},

    "11950H":           {"core": 8,  "threads": 16, "p": 8, "e": 0, "lp": 0},
}

In [962]:
def fill_cpu_specs(row):
    model = row["processor_model"]
    if pd.isna(model):
        return row

    model = str(model).strip()

    if model in cpu_lookup:
        spec = cpu_lookup[model]
        row["core_count"] = spec["core"]
        row["threads_count"] = spec["threads"]
        row["p_cores"] = spec["p"]
        row["e_cores"] = spec["e"]
        row["lp_e_cores"] = spec["lp"]

    return row

df1 = df1.apply(fill_cpu_specs, axis=1)

In [963]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         0
display_height        0
display_size          0
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      0
processor_series      0
processor_model       0
processor_suffix    133
core_count            0
threads_count        50
p_cores             270
e_cores             292
lp_e_cores          810
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
dtype: int64

In [964]:
df1[df1["threads_count"].isna()]

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type
24,lenovo,Lenovo LOQ 15IRX9 83DV018LIN Gaming Laptop (13...,104990,71,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),24,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",8 GB NVIDIA GeForce RTX 4060,Windows,1.0,Intel,Core,Core I7,13650HX,HX,14.0,NaN,6.0,8.0,NaN,NVIDIA,GeForce RTX,RTX 4060,8.0,False,LOQ 15IRX9,Gaming
29,apple,Apple MacBook Pro 14 Laptop (Apple M5/ 24GB/ 1...,202990,55,Apple M5,10 Cores (4P + 6E),24,1024,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",10 Core GPU,Mac,1.0,Apple,M-Series,M5,M5,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,10 Core GPU,NaN,True,MacBook Pro 14,General
30,apple,Apple MacBook Pro 14 Laptop (Apple M5/ 16GB/ 1...,183490,53,Apple M5,10 Cores (4P + 6E),16,1024,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",10 Core GPU,Mac,1.0,Apple,M-Series,M5,M5,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,10 Core GPU,NaN,True,MacBook Pro 14,General
31,apple,Apple MacBook Pro 14 2025 Laptop (Apple M5/ 16...,164490,51,Apple M5,10 Cores (4P + 6E),16,512,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",10 Core GPU,Mac,1.0,Apple,M-Series,M5,M5,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,10 Core GPU,NaN,True,MacBook Pro 14 2025,General
205,samsung,Samsung Galaxy Book 5 np750xhd-kd3in Laptop (I...,103990,65,Intel Core Ultra 7 Series 2 255U,12 Cores (2P + 8E + 2LP-E),16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Intel Graphics,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255U,U,12.0,NaN,2.0,8.0,2.0,Intel,Integrated Graphics,Intel Integrated Graphics,NaN,True,Galaxy Book 5,General
206,samsung,Samsung Galaxy Book 5 NP750XHD-KD2IN Laptop (I...,87990,63,Intel Core Ultra 7 Series 2 255U,12 Cores (2P + 8E + 2LP-E),16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Intel Graphics,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255U,U,12.0,NaN,2.0,8.0,2.0,Intel,Integrated Graphics,Intel Integrated Graphics,NaN,True,Galaxy Book 5,General
434,asus,Asus TUF Gaming A16 FA608PP-QT014WS Laptop (AM...,159990,81,8th Gen AMD Ryzen 9 8940HX,16 Cores,16,1024,2560,1600,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA GeForce RTX 5070,Windows,1.0,AMD,Ryzen,Ryzen 9,8940HX,HX,16.0,NaN,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 5070,8.0,False,TUF Gaming A16,Gaming
442,lenovo,Lenovo LOQ ‎15IRX9 83DV00X8IN Gaming Laptop (1...,117990,71,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),24,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",8 GB NVIDIA GeForce RTX 4060,Windows,1.0,Intel,Core,Core I7,13650HX,HX,14.0,NaN,6.0,8.0,NaN,NVIDIA,GeForce RTX,RTX 4060,8.0,False,LOQ ‎15IRX9,Gaming
608,asus,Asus ROG Strix G16 G614JU-N4200WS Gaming Lapto...,135990,71,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),16,1024,1920,1200,16,"16 inches, 1920 x 1200 pixels",6 GB NVIDIA GeForce RTX 4050,Windows,1.0,Intel,Core,Core I7,13650HX,HX,14.0,NaN,6.0,8.0,NaN,NVIDIA,GeForce RTX,RTX 4050,6.0,False,ROG Strix G16,Gaming
626,lenovo,Lenovo Legion 5 15IRX9 83JJ0010IN Gaming Lapto...,122990,70,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),24,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",8 GB NVIDIA GeForce RTX 4060,Windows,1.0,Intel,Core,Core I7,13650HX,HX,14.0,NaN,6.0,8.0,NaN,NVIDIA,GeForce RTX,RTX 4060,8.0,False,Legion 5 15IRX9,Gaming
641,lenovo,Lenovo Yoga Slim 7 14Q8X9 83ED0065IN Laptop (S...,92990,60,Qualcomm Snapdragon X Plus X1P-64-100,10 Cores,32,1024,2944,1840,14.5,"14.5 inches, 2944 x 1840 pixels, Touch Screen",Integrated Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-64-100,None,10.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Yoga Slim 7 14Q8X9,Convertible
643,apple,Apple MacBook Air M4 2025 15 Laptop (Apple M4/...,157490,52,Apple M4,10 Cores (4P + 6E),24,512,2880,1864,15.3,"15.3 inches, 2880 x 1864 pixels",Apple 10 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,Apple 10 Core GPU,NaN,True,MacBook Air M4 2025 15,Thin & Light
644,apple,Apple MacBook Air 2025 15 Laptop (Apple M4/ 16...,138490,50,Apple M4,10 Cores (4P + 6E),16,512,2880,1864,15.3,"15.3 inches, 2880 x 1864 pixels",Apple 10 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,Apple 10 Core GPU,NaN,True,MacBook Air 2025 15,Thin & Light
645,apple,Apple MacBook Air 15 2025 Laptop (Apple M4/ 16...,119490,46,Apple M4,10 Cores (4P + 6E),16,256,2880,1864,15.3,"15.3 inches, 2880 x 1864 pixels",Apple 10 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,Apple 10 Core GPU,NaN,True,MacBook Air 15 2025,Thin & Light
646,apple,Apple MacBook Air 2025 Laptop (Apple M4/ 24GB/...,130900,50,Apple M4,10 Cores (4P + 6E),24,512,2560,1664,13.6,"13.6 inches, 2560 x 1664 pixels",Apple 10 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,Apple 10 Core GPU,NaN,True,MacBook Air 2025,Thin & Light
647,apple,Apple MacBook Air 2025 Laptop (Apple M4/ 16GB/...,110900,47,Apple M4,10 Cores (4P + 6E),16,512,2560,1664,13.6,"13.6 inches, 2560 x 1664 pixels",Apple 10 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,Apple 10 Core GPU,NaN,True,MacBook Air 2025,Thin & Light
659,lenovo,Lenovo LOQ ‎15IRX9 83DV00XEIN Gaming Laptop (1...,91790,66,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",6 GB NVIDIA GeForce RTX 3050,Windows,1.0,Intel,Core,Core I7,13650HX,HX,14.0,NaN,6.0,8.0,NaN,NVIDIA,GeForce RTX,RTX 3050,6.0,False,LOQ ‎15IRX9,Gaming
754,dell,Dell 14 Inspiron 5441 Laptop (Snapdragon X Plu...,91490,43,Qualcomm Snapdragon X Plus X1P-64-100,10 Cores,16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-64-100,None,10.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,14 Inspiron 5441,Thin & Light
776,apple,Apple 2024 MacBook Air 15 Laptop (Apple M3/ 16...,104994,56,Apple M3,Octa Core (4P + 4E),16,256,2880,1864,15.3,"15.3 inches, 2880 x 1864 pixels",10-Core GPU,Mac,1.0,Apple,M-Series,M3,M3,None,8.0,NaN,4.0,4.0,NaN,Apple,Apple GPU,10-Core GPU,NaN,True,2024 MacBook Air 15,Thin & Light
777,apple,Apple MacBook Air 13 2024 Laptop (Apple M3/ 24...,127653,53,Apple M3,Octa Core (4P + 4E),24,512,2560,1664,13.6,"13.6 inches, 2560 x 1664 pixels",Apple 10 Core GPU,Mac,1.0,Apple,M-Series,M3,M3,None,8.0,NaN,4.0,4.0,NaN,Apple,Apple GPU,Apple 10 Core GPU,NaN,True,MacBook Air 13 2024,Thin & Light
778,apple,Apple MacBook Air 15 2024 Laptop (Apple M3/ 24...,154287,60,Apple M3,Octa Core (4P + 4E),24,512,2880,1864,15.3,"15.3 inches, 2880 x 1864 pixels",10-Core GPU,Mac,1.0,Apple,M-Series,M3,M3,None,8.0,NaN,4.0,4.0,NaN,Apple,Apple GPU,10-Core GPU,NaN,True,MacBook Air 15 2024,Thin & Light
779,apple,Apple MacBook Pro 16 Laptop (Apple M4 Max/ 36 ...,349900,65,Apple M4 Max,14 Cores (10P + 4E),36,1024,3456,2234,16.2,"16.2 inches, 3456 x 2234 pixels",32 Core GPU,Mac,1.0,Apple,M-Series,M4,M4 Max,Max,14.0,NaN,10.0,4.0,NaN,Apple,Apple GPU,32 Core GPU,NaN,True,MacBook Pro 16,General
785,apple,Apple MacBook Pro 16 Laptop (Apple M4 Pro/ 48G...,279990,64,Apple M4 Pro,14 Cores (10P + 4E),48,512,3456,2234,16.2,"16.2 inches, 3456 x 2234 pixels",20 Core GPU,Mac,1.0,Apple,M-Series,M4,M4 Pro,Pro,14.0,NaN,10.0,4.0,NaN,Apple,Apple GPU,20 Core GPU,NaN,True,MacBook Pro 16,General
786,apple,Apple MacBook Pro 16 2024 Laptop (Apple M4 Pro...,239990,60,Apple M4 Pro,14 Cores (10P + 4E),24,512,3456,2234,16.2,"16.2 inches, 3456 x 2234 pixels",20 Core GPU,Mac,1.0,Apple,M-Series,M4,M4 Pro,Pro,14.0,NaN,10.0,4.0,NaN,Apple,Apple GPU,20 Core GPU,NaN,True,MacBook Pro 16 2024,General
787,apple,Apple MacBook Pro 14 Laptop (Apple M4 MAX/ 36G...,289990,63,Apple M4 Max,14 Cores (10P + 4E),36,1024,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",32 Core GPU,Mac,1.0,Apple,M-Series,M4,M4 Max,Max,14.0,NaN,10.0,4.0,NaN,Apple,Apple GPU,32 Core GPU,NaN,True,MacBook Pro 14,General
788,apple,Apple MacBook Pro 14 Laptop (Apple M4 Pro/ 24G...,225990,60,Apple M4 Pro,14 Cores (10P + 4E),24,1024,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",20 Core GPU,Mac,1.0,Apple,M-Series,M4,M4 Pro,Pro,14.0,NaN,10.0,4.0,NaN,Apple,Apple GPU,20 Core GPU,NaN,True,MacBook Pro 14,General
789,apple,Apple MacBook Pro 14 Laptop (Apple M4 Pro/ 24G...,187990,57,Apple M4 Pro,12 Cores (8P + 4E),24,512,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",16 Core GPU,Mac,1.0,Apple,M-Series,M4,M4 Pro,Pro,12.0,NaN,8.0,4.0,NaN,Apple,Apple GPU,16 Core GPU,NaN,True,MacBook Pro 14,General
790,apple,Apple MacBook Pro 14 Laptop (Apple M4/ 24GB/ 1...,201990,59,Apple M4,10 Cores (4P + 6E),24,1024,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",10 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,10 Core GPU,NaN,True,MacBook Pro 14,General
791,apple,Apple MacBook Pro 14 Laptop (Apple M4/ 16GB/ 1...,182990,55,Apple M4,10 Cores (4P + 6E),16,1024,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",10 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,10 Core GPU,NaN,True,MacBook Pro 14,General
792,apple,Apple MacBook Pro 14 2024 Laptop (Apple M4/ 16...,159900,54,Apple M4,10 Cores (4P + 6E),16,512,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",10 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,10 Core GPU,NaN,True,MacBook Pro 14 2024,General
809,apple,Apple MacBook Air 2025 Laptop (Apple M4/ 16GB/...,93900,45,Apple M4,10 Cores (4P + 6E),16,256,2560,1664,13.6,"13.6 inches, 2560 x 1664 pixels",Apple 8 Core GPU,Mac,1.0,Apple,M-Series,M4,M4,None,10.0,NaN,4.0,6.0,NaN,Apple,Apple GPU,Apple 8 Core GPU,NaN,True,MacBook Air 2025,Thin & Light
839,lenovo,Lenovo Legion 5 15IRX9 83JJ000DIN Gaming Lapto...,135690,69,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),24,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",8 GB NVIDIA GeForce RTX 4060,Windows,1.0,Intel,Core,Core I7,13650HX,HX,14.0,NaN,6.0,8.0,NaN,NVIDIA,GeForce RTX,RTX 4060,8.0,False,Legion 5 15IRX9,Gaming
875,lenovo,Lenovo Yoga Slim 7x 14Q8X9 83ED003BIN Laptop (...,139990,59,Qualcomm Snapdragon X Elite X1E-78-100,12 Cores,32,1024,2944,1840,14.5,"14.5 inches, 2944 x 1840 pixels, Touch Screen",Qualcomm Adreno,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite X1E-78-100,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno GPU,NaN,True,Yoga Slim 7x 14Q8X9,Convertible
887,dell,Dell Inspiron 14 Plus OIN7441200101RINU1 AI La...,88990,56,Qualcomm Snapdragon X Plus X1P-64-100,10 Cores,16,512,2560,1600,14,"14 inches, 2560 x 1600 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-64-100,None,10.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Inspiron 14 Plus,Thin & Light
896,gigabyte,Gigabyte G6X 9MG-42IN854SH Gaming Laptop (13th...,170000,69,13th Gen Intel Core i7 13650HX,14 Cores (6P + 8E),16,1024,1920,1200,16,"16 inches, 1920 x 1200 pixels",6 GB NVIDIA GeForce RTX 4050,Windows,2.0,Intel,Core,Core I7,13650HX,HX,14.0,NaN,6.0,8.0,NaN,NVIDIA,GeForce RTX,RTX 4050,6.0,False,G6X,Gaming
899,apple,Apple MacBook Air 13 2024 Laptop (Apple M3/ 16...,107299,47,Apple M3,Octa Core (4P + 4E),16,256,2560,1664,13.6,"13.6 inches, 2560 x 1664 pixels",Apple 10 Core GPU,Mac,1.0,Apple,M-Series,M3,M3,None,8.0,NaN,4.0,4.0,NaN,Apple,Apple GPU,Apple 10 Core GPU,NaN,True,MacBook Air 13 2024,Thin & Light
913,dell,Dell Inspiron 14 Plus AI Laptop (Snapdragon X ...,111490,57,Qualcomm Snapdragon X Plus X1P-64-100,10 Cores,16,1024,2560,1600,14,"14 inches, 2560 x 1600 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-64-100,None,10.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Inspiron 14 Plus AI,Thin & Light
930,hp,HP OmniBook X 14-fe0121QU AI Laptop (Snapdrago...,126117,56,Qualcomm Snapdragon X Elite X1E-78-100,12 Cores,16,1024,2240,1400,14,"14 inches, 2240 x 1400 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite X1E-78-100,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,OmniBook X,Thin & Light
953,dell,Dell XPS 9345 AI Laptop (Snapdragon X Elite X1...,179490,74,Qualcomm Snapdragon X Elite X1E-80-100,12 Cores,32,1024,2880,1800,13.4,"13.4 inches, 2880 x 1800 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite X1E-80-100,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,XPS 9345 AI,Thin & Light
954,dell,Dell XPS 9345 AI Laptops (Snapdragon X Elite/ ...,159990,69,Qualcomm Snapdragon X Elite X1E-80-100,12 Cores,16,512,2880,1800,13.4,"13.4 inches, 2880 x 1800 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite X1E-80-100,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,XPS 9345 AI Laptops,Thin & Light
959,microsoft,Microsoft Surface Laptop 7 15 ‎ZHH-00048 (Snap...,144008,48,Qualcomm Snapdragon X Elite,12 Cores,16,512,2496,1664,15,"15 inches, 2496 x 1664 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Surface,Thin & Light
960,microsoft,Microsoft Surface Pro 11 ‎ZIB-00031 Laptop (Sn...,174099,53,Qualcomm Snapdragon X Elite,12 Cores,16,1024,2880,1920,13,"13 inches, 2880 x 1920 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Surface Pro 11,Thin & Light
961,microsoft,Microsoft Surface Pro 11 2024 ‎ZID-00014 Lapto...,224099,59,Qualcomm Snapdragon X Elite,12 Cores,32,1024,2880,1920,13,"13 inches, 2880 x 1920 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Surface Pro 11 2024,Thin & Light
963,microsoft,Microsoft Surface Laptop 7 13.8 ‎‎ZGQ-00023 (S...,202990,52,Qualcomm Snapdragon X Elite,12 Cores,32,1024,2304,1536,13.8,"13.8 inches, 2304 x 1536 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Surface,Thin & Light
964,microsoft,Microsoft Surface Laptop 7 ‎ZXX-00059 (Snapdra...,170990,46,Qualcomm Snapdragon X Elite,12 Cores,16,1024,2304,1536,13.8,"13.8 inches, 2304 x 1536 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Surface,Thin & Light
965,microsoft,Microsoft Surface Laptop 7 15 ‎‎ZYT-00048 (Sna...,156774,50,Qualcomm Snapdragon X Elite,12 Cores,16,1024,2496,1664,15,"15 inches, 2496 x 1664 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Surface,Thin & Light
966,microsoft,Microsoft Surface Laptop 7 15 ‎ZHG-00023 (Snap...,134000,45,Qualcomm Snapdragon X Elite,12 Cores,16,256,2496,1664,15,"15 inches, 2496 x 1664 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Surface,Thin & Light
970,dell,Dell Inspiron 7441 Plus AI Laptop (Snapdragon ...,96448,56,Qualcomm Snapdragon X Plus X1P-64-100,10 Cores,16,512,2560,1600,14,"14 inches, 2560 x 1600 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-64-100,None,10.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Inspiron 7441 Plus AI,Thin & Light
971,dell,Dell Inspiron 7441 Plus AI Laptop (Snapdragon ...,96448,56,Qualcomm Snapdragon X Plus X1P-64-100,10 Cores,16,512,2560,1600,14,"14 inches, 2560 x 1600 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1P-64-100,None,10.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Inspiron 7441 Plus AI,Thin & Light
972,dell,Dell XPS 13 9345 AI Laptops (Snapdragon X Plus...,144990,55,Qualcomm Snapdragon X Plus X1E-80-100,12 Cores,16,512,1920,1200,13.4,"13.4 inches, 1920 x 1200 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1E-80-100,None,12.0,NaN,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,XPS 13 9345 AI Laptops,Thin & Light

In [965]:
import numpy as np
import pandas as pd

# Work on a copy just in case
df1 = df1.copy()

# Only rows where threads_count is missing
mask_missing = df1["threads_count"].isna()

# ---------- 1) Intel hybrid: use P/E/LP-E breakdown ----------
mask_intel = (
    mask_missing
    & df1["processor_brand"].eq("Intel")
    & df1["p_cores"].notna()
)

df1.loc[mask_intel, "threads_count"] = (
    2 * df1.loc[mask_intel, "p_cores"].astype(float)
    + df1.loc[mask_intel, "e_cores"].fillna(0).astype(float)
    + df1.loc[mask_intel, "lp_e_cores"].fillna(0).astype(float)
)

# ---------- 2) Apple M-series: 1 thread per core ----------
mask_apple = (
    mask_missing
    & df1["processor_brand"].eq("Apple")
    & df1["core_count"].notna()
)

df1.loc[mask_apple, "threads_count"] = df1.loc[mask_apple, "core_count"]

# ---------- 3) AMD Ryzen / Ryzen AI: SMT2 (2 threads per core) ----------
mask_amd = (
    mask_missing
    & df1["processor_brand"].eq("AMD")
    & df1["core_count"].notna()
)

df1.loc[mask_amd, "threads_count"] = 2 * df1.loc[mask_amd, "core_count"]

# ---------- 4) Snapdragon X (Elite / Plus): 1 thread per core ----------
mask_snap = (
    mask_missing
    & df1["processor_brand"].eq("Snapdragon")
    & df1["core_count"].notna()
)

df1.loc[mask_snap, "threads_count"] = df1.loc[mask_snap, "core_count"]

# Optionally convert to float/int
df1["threads_count"] = df1["threads_count"].astype("float")

In [966]:
df1.loc[[24, 205, 434, 641, 643, 776, 875, 959], 
        ["processor", "processor_brand", "core_count", "threads_count"]]

,processor,processor_brand,core_count,threads_count
24,13th Gen Intel Core i7 13650HX,Intel,14.0,20.0
205,Intel Core Ultra 7 Series 2 255U,Intel,12.0,14.0
434,8th Gen AMD Ryzen 9 8940HX,AMD,16.0,32.0
641,Qualcomm Snapdragon X Plus X1P-64-100,Snapdragon,10.0,10.0
643,Apple M4,Apple,10.0,10.0
776,Apple M3,Apple,8.0,8.0
875,Qualcomm Snapdragon X Elite X1E-78-100,Snapdragon,12.0,12.0
959,Qualcomm Snapdragon X Elite,Snapdragon,12.0,12.0

In [969]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         0
display_height        0
display_size          0
display               0
graphics              6
os                    0
warranty              3
processor_brand       0
processor_family      0
processor_series      0
processor_model       0
processor_suffix    133
core_count            0
threads_count         0
p_cores             270
e_cores             292
lp_e_cores          810
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
dtype: int64

In [976]:
df1[df1["warranty"].isna()]

Empty DataFrame
Columns: [brand, model, price, rating, processor, cores, ram, storage, display_width, display_height, display_size, display, graphics, os, warranty, processor_brand, processor_family, processor_series, processor_model, processor_suffix, core_count, threads_count, p_cores, e_cores, lp_e_cores, gpu_brand, gpu_series, gpu_model, gpu_vram, is_integrated, series_name, device_type]
Index: []

In [975]:
# assuming df1 is your main dataframe
df1["warranty"] = df1["warranty"].fillna(1.0)

In [977]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         0
display_height        0
display_size          0
display               0
graphics              6
os                    0
warranty              0
processor_brand       0
processor_family      0
processor_series      0
processor_model       0
processor_suffix    133
core_count            0
threads_count         0
p_cores             270
e_cores             292
lp_e_cores          810
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
dtype: int64

In [978]:
df1[df1["processor_suffix"].isna()]

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type
11,ultimus,Ultimus Apex Bold N NU14U9INC54LS Laptop (Cele...,16990,33,Intel Celeron N4020,"Dual Core, 2 Threads",8,256,1366,768,14.1,"14.1 inches, 1366 x 768 pixels",Intel Integrated,Windows,1.0,Intel,Celeron,Celeron,N4020,None,2.0,2.0,NaN,NaN,NaN,Intel,Integrated Graphics,Intel Integrated Graphics,NaN,True,Apex Bold N,General
14,msi,MSI VenturePro A15 A3HWEG-011IN Laptop (AMD Ry...,124990,70,AMD Ryzen 7 350,"Octa Core, 16 Threads",16,1024,1920,1080,16,"16 inches, 1920 x 1080 pixels",8 GB NVIDIA GeForce RTX 5050,Windows,2.0,AMD,Ryzen,Ryzen 7,350,None,8.0,16.0,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 5050,8.0,False,VenturePro A15,General
27,dell,Dell 16 Plus DB16255 Next Gen AI Laptop (AMD R...,71490,55,5th Gen AMD Ryzen 5 AI 340,"Hexa Core, 12 Threads",16,512,1920,1200,16,"16 inches, 1920 x 1200 pixels",Intel Integrated Arc,Windows,1.0,AMD,Ryzen,Ryzen 5,340,None,8.0,16.0,0.0,8.0,0.0,Intel,Arc,Arc Graphics,NaN,True,16 Plus,General
29,apple,Apple MacBook Pro 14 Laptop (Apple M5/ 24GB/ 1...,202990,55,Apple M5,10 Cores (4P + 6E),24,1024,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",10 Core GPU,Mac,1.0,Apple,M-Series,M5,M5,None,10.0,10.0,4.0,6.0,NaN,Apple,Apple GPU,10 Core GPU,NaN,True,MacBook Pro 14,General
30,apple,Apple MacBook Pro 14 Laptop (Apple M5/ 16GB/ 1...,183490,53,Apple M5,10 Cores (4P + 6E),16,1024,3024,1964,14.2,"14.2 inches, 3024 x 1964 pixels",10 Core GPU,Mac,1.0,Apple,M-Series,M5,M5,None,10.0,10.0,4.0,6.0,NaN,Apple,Apple GPU,10 Core GPU,NaN,True,MacBook Pro 14,General
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
972,dell,Dell XPS 13 9345 AI Laptops (Snapdragon X Plus...,144990,55,Qualcomm Snapdragon X Plus X1E-80-100,12 Cores,16,512,1920,1200,13.4,"13.4 inches, 1920 x 1200 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Plus X1E-80-100,None,12.0,12.0,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,XPS 13 9345 AI Laptops,Thin & Light
999,asus,Asus Vivobook Go 15 E510KA-EJ011WS Laptop (Int...,24990,46,Intel Celeron N4500,"Dual Core, 2 Threads",8,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Intel HD Graphics,Windows,1.0,Intel,Celeron,Celeron,N4500,None,2.0,2.0,NaN,NaN,NaN,Intel,HD,HD Graphics,NaN,True,Vivobook Go 15,Thin & Light
1001,asus,Asus Chromebook CX1500CKA-NJ0395 Laptop (Celer...,26999,36,Intel Celeron N4500,"Dual Core, 2 Threads",8,128,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Intel Integrated UHD,Chrome,1.0,Intel,Celeron,Celeron,N4500,None,2.0,2.0,NaN,NaN,NaN,Intel,UHD,UHD Graphics,NaN,True,Chromebook,General
1007,asus,Asus Vivobook S 15 OLED 2024 S5507QAD-MA751WS ...,84834,53,Qualcomm Snapdragon X Elite X1E 78 100,"12 Cores, 12 Threads",16,1024,2880,1620,15.6,"15.6 inches, 2880 x 1620 pixels",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite X1E 78 100,None,12.0,12.0,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Vivobook S 15 OLED 2024,Thin & Light
1009,lenovo,Lenovo IdeaPad 1 14IGL7 82V6009LIN Laptop (Cel...,28802,46,4th Gen Intel Celeron N4020,"Dual Core, 2 Threads",8,512,1366,768,14,"14 inches, 1366 x 768 pixels",Intel Integrated UHD,Windows,1.0,Intel,Celeron,Celeron,N4020,None,2.0,2.0,NaN,NaN,NaN,Intel,UHD,UHD Graphics,NaN,True,IdeaPad 1 14IGL7,General

In [979]:
df1["has_touchscreen"] = df1["display"].str.contains("touch", case=False, na=False)

In [980]:
df1[["display", "has_touchscreen"]].head(20)

                            display  has_touchscreen
0     16 inches, 2560 x 1600 pixels            False
1   15.6 inches, 1920 x 1080 pixels            False
2   15.6 inches, 1920 x 1080 pixels            False
3     14 inches, 1920 x 1080 pixels            False
4     14 inches, 1920 x 1080 pixels            False
5     14 inches, 1920 x 1080 pixels            False
6     14 inches, 1920 x 1080 pixels            False
7     14 inches, 1920 x 1080 pixels            False
8   15.6 inches, 1920 x 1080 pixels            False
9   15.6 inches, 1920 x 1080 pixels            False
10    14 inches, 1920 x 1080 pixels            False
11   14.1 inches, 1366 x 768 pixels            False
12    14 inches, 1920 x 1080 pixels            False
13  15.6 inches, 1920 x 1080 pixels            False
14    16 inches, 1920 x 1080 pixels            False
15  15.6 inches, 1920 x 1080 pixels            False
16    14 inches, 1920 x 1200 pixels            False
17  15.6 inches, 1920 x 1080 pixels            False
18  15.6 inches, 1920 x 1080 pixels            False
19    14 inches, 2560 x 1600 pixels            False

In [984]:
df1.sample(10)

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type,has_touchscreen
471,lenovo,Lenovo IdeaPad Slim 3 82RK019DIN Laptop (12th ...,35600,47,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Intel Integrated,Windows,1.0,Intel,Core,Core I3,1215U,U,6.0,8.0,2.0,4.0,NaN,Intel,Integrated Graphics,Intel Integrated Graphics,NaN,True,IdeaPad Slim 3,Thin & Light,False
243,acer,Acer 14 Travel Lite TL14-52M Laptop (13th Gen ...,39990,56,13th Gen Intel Core i3 1305U,"5 Cores (1P + 4E), 6 Threads",16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",‎Intel Graphics,Windows,1.0,Intel,Core,Core I3,1305U,U,5.0,6.0,1.0,4.0,NaN,Intel,Integrated Graphics,Intel Integrated Graphics,NaN,True,14 Travel Lite,General,False
322,acer,Acer 2025 Predator Helios Neo16S AI PHN16S-71 ...,149999,75,Intel Core Ultra 7 255HX,"20 Cores (8P + 12E), 20 Threads",16,1024,2560,1600,16,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA GeForce RTX 5050,Windows,1.0,Intel,Core Ultra,Core Ultra 7,255HX,HX,20.0,20.0,8.0,12.0,NaN,NVIDIA,GeForce RTX,RTX 5050,8.0,False,2025 Predator Helios Neo16S AI,Gaming,False
756,acer,Acer Nitro V ANV15-41 NH.QPFSI.006 Gaming Lapt...,61490,62,6th Gen AMD Ryzen 5 6600H,"Hexa Core, 12 Threads",16,512,1920,1080,16,"16 inches, 1920 x 1080 pixels",6 GB NVIDIA GeForce RTX 3050,Windows,1.0,AMD,Ryzen,Ryzen 5,6600H,H,6.0,12.0,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 3050,6.0,False,Nitro V,Gaming,False
27,dell,Dell 16 Plus DB16255 Next Gen AI Laptop (AMD R...,71490,55,5th Gen AMD Ryzen 5 AI 340,"Hexa Core, 12 Threads",16,512,1920,1200,16,"16 inches, 1920 x 1200 pixels",Intel Integrated Arc,Windows,1.0,AMD,Ryzen,Ryzen 5,340,None,8.0,16.0,0.0,8.0,0.0,Intel,Arc,Arc Graphics,NaN,True,16 Plus,General,False
931,lenovo,Lenovo IdeaPad 1 15ALC7 82R400EFIN Laptop (AMD...,41999,57,5th Gen AMD Ryzen 7 5700U,"Octa Core, 16 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",AMD Radeon,Windows,1.0,AMD,Ryzen,Ryzen 7,5700U,U,8.0,16.0,NaN,NaN,NaN,AMD,Radeon,Radeon,NaN,True,IdeaPad 1 15ALC7,General,False
330,acer,Acer Nitro Lite NL16-71G NH.D59SI.002 Gaming L...,74999,64,13th Gen Intel Core i7 13620H,"10 Cores (6P + 4E), 16 Threads",16,512,1920,1200,16,"16 inches, 1920 x 1200 pixels",6 GB NVIDIA GeForce RTX 3050,Windows,1.0,Intel,Core,Core I7,13620H,H,10.0,16.0,6.0,4.0,NaN,NVIDIA,GeForce RTX,RTX 3050,6.0,False,Nitro Lite,Gaming,False
183,hp,HP OmniBook X Flip 14-fm0099TU Next Gen AI Lap...,104990,72,Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,1024,2880,1800,14,"14 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc 130V GPU (8GB),Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc 130V GPU (8GB),8.0,False,OmniBook X Flip,Convertible,True
863,asus,Asus TUF Gaming A15 2024 FA507UV-LP137WS Gamin...,109990,75,8th Gen AMD Ryzen 9 8945H,"Octa Core, 16 Threads",16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",8 GB NVIDIA GeForce RTX 4060,Windows,1.0,AMD,Ryzen,Ryzen 9,8945H,H,8.0,16.0,NaN,NaN,NaN,NVIDIA,GeForce RTX,RTX 4060,8.0,False,TUF Gaming A15 2024,Gaming,False
965,microsoft,Microsoft Surface Laptop 7 15 ‎‎ZYT-00048 (Sna...,156774,50,Qualcomm Snapdragon X Elite,12 Cores,16,1024,2496,1664,15,"15 inches, 2496 x 1664 pixels, Touch Screen",Qualcomm Adreno GPU,Windows,1.0,Snapdragon,Snapdragon,Snapdragon X,Elite,None,12.0,12.0,NaN,NaN,NaN,Qualcomm,Adreno,Adreno Gpu,NaN,True,Surface,Thin & Light,True

In [990]:
df1["processor_series"].unique()

array(['Core Ultra 7', 'Core I5', 'Ryzen 3', 'Core I7', 'Core 5',
       'Core I3', 'Ryzen 5', 'Celeron', 'Ryzen 7', 'Core 7',
       'Core Ultra 9', 'Core Ultra 5', 'M5', 'Snapdragon X', 'Ryzen 9',
       'Ryzen Ai 5', 'Ryzen Ai 7', 'Core 3', '210H', 'Core I9',
       'Ryzen Ai 9', 'Ryzen Ai Max', 'M4', 'M3'], dtype=object)

In [993]:
total_count = df1["processor_series"].isin(
    ["Ryzen Ai 5","Ryzen Ai 7","Ryzen Ai 9","Ryzen Ai Max","Snapdragon X","Celeron","M4","M3","M5"]
).sum()

total_count

np.int64(127)

In [992]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         0
display_height        0
display_size          0
display               0
graphics              6
os                    0
warranty              0
processor_brand       0
processor_family      0
processor_series      0
processor_model       0
processor_suffix    133
core_count            0
threads_count         0
p_cores             270
e_cores             292
lp_e_cores          810
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
has_touchscreen       0
dtype: int64

In [994]:
df1["processor_suffix"].unique()

array(['HX', 'H', 'U', None, 'HS', 'V', 'Y', 'C', 'G7', 'Max', 'Pro', 'P'],
      dtype=object)

In [1000]:
df1[df1["processor_model"]=="1135G7"]

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type,has_touchscreen
744,dell,Dell Latitude 3420 GD723ZG84 Laptop (11th Gen ...,55990,44,11th Gen Intel Core i5,11th Gen Intel Core i5,16,512,1920,1080,14,"14 inches, 1920 x 1080 pixels",Intel Integrated Graphics,Ubuntu,3.0,Intel,Core,Core I5,1135G7,G7,4.0,8.0,4.0,0.0,0.0,Intel,Integrated Graphics,Intel Integrated Graphics,NaN,True,Latitude 3420,Business,False
933,acer,Acer TravelMate TMP215-53 Laptop (11th Gen Cor...,60780,57,11th Gen Intel Core i5 1135G7,"Quad Core, 8 Threads",8,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels",Iris Xe Graphics,Windows,1.0,Intel,Core,Core I5,1135G7,G7,4.0,8.0,NaN,NaN,NaN,Intel,Iris Xe,Iris Xe Graphics,NaN,True,TravelMate,General,False

In [999]:
df1.loc[933, "processor_suffix"] = "G7"

In [1001]:
mask = df1["processor_brand"].str.lower() == "snapdragon"

df1.loc[mask, ["p_cores", "e_cores", "lp_e_cores"]] = None

In [1002]:
df1[df1["processor_brand"] == "Snapdragon"][["processor_brand", "p_cores", "e_cores", "lp_e_cores"]]

     processor_brand  p_cores  e_cores  lp_e_cores
50        Snapdragon      NaN      NaN         NaN
57        Snapdragon      NaN      NaN         NaN
58        Snapdragon      NaN      NaN         NaN
73        Snapdragon      NaN      NaN         NaN
234       Snapdragon      NaN      NaN         NaN
309       Snapdragon      NaN      NaN         NaN
314       Snapdragon      NaN      NaN         NaN
402       Snapdragon      NaN      NaN         NaN
403       Snapdragon      NaN      NaN         NaN
417       Snapdragon      NaN      NaN         NaN
516       Snapdragon      NaN      NaN         NaN
641       Snapdragon      NaN      NaN         NaN
664       Snapdragon      NaN      NaN         NaN
665       Snapdragon      NaN      NaN         NaN
666       Snapdragon      NaN      NaN         NaN
754       Snapdragon      NaN      NaN         NaN
761       Snapdragon      NaN      NaN         NaN
764       Snapdragon      NaN      NaN         NaN
784       Snapdragon      NaN      NaN         NaN
826       Snapdragon      NaN      NaN         NaN
865       Snapdragon      NaN      NaN         NaN
875       Snapdragon      NaN      NaN         NaN
887       Snapdragon      NaN      NaN         NaN
913       Snapdragon      NaN      NaN         NaN
930       Snapdragon      NaN      NaN         NaN
953       Snapdragon      NaN      NaN         NaN
954       Snapdragon      NaN      NaN         NaN
959       Snapdragon      NaN      NaN         NaN
960       Snapdragon      NaN      NaN         NaN
961       Snapdragon      NaN      NaN         NaN
962       Snapdragon      NaN      NaN         NaN
963       Snapdragon      NaN      NaN         NaN
964       Snapdragon      NaN      NaN         NaN
965       Snapdragon      NaN      NaN         NaN
966       Snapdragon      NaN      NaN         NaN
967       Snapdragon      NaN      NaN         NaN
970       Snapdragon      NaN      NaN         NaN
971       Snapdragon      NaN      NaN         NaN
972       Snapdragon      NaN      NaN         NaN
1007      Snapdragon      NaN      NaN         NaN

In [1004]:
df1["processor_family"].unique()

array(['Core Ultra', 'Core', 'Ryzen', 'Celeron', 'M-Series', 'Snapdragon',
       'Core 5'], dtype=object)

In [1007]:
df1["processor_family"].isin(["Ryzen","Celeron","Snapdragon"]).sum()

np.int64(300)

In [1017]:
df1["p_cores"].isna().sum()

np.int64(290)

In [1012]:
# --- define the final useful columns ---
final_columns = [
    "brand",
    "model",
    "price",
    "rating",

    "processor",
    "processor_brand",
    "processor_family",
    "processor_series",
    "processor_model",
    "processor_suffix",
    "core_count",
    "threads_count",
    "p_cores",
    "e_cores",
    "lp_e_cores",

    "ram",
    "storage",

    "display_width",
    "display_height",
    "display_size",
    "has_touchscreen",
    "display",

    "graphics",
    "gpu_brand",
    "gpu_series",
    "gpu_model",
    "gpu_vram",
    "is_integrated",

    "os",
    "warranty",

    "series_name",
    "device_type",
]

# --- keep only available columns (ignore missing ones safely) ---
final_columns = [col for col in final_columns if col in df1.columns]

# --- Create final cleaned dataframe ---
df_final = df1[final_columns].copy()

df_final.head()

,brand,model,price,rating,processor,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,ram,storage,display_width,display_height,display_size,has_touchscreen,display,graphics,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,os,warranty,series_name,device_type
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,189990,84,Intel Core Ultra 7 255HX,Intel,Core Ultra,Core Ultra 7,255HX,HX,20.0,20.0,8.0,12.0,NaN,32,1024,2560,1600,16,False,"16 inches, 2560 x 1600 pixels",8 GB NVIDIA® GeForce RTX 5060,NVIDIA,GeForce RTX,RTX 5060,8.0,False,Windows,1.0,Legion Pro 5,Gaming
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,62350,54,13th Gen Intel Core i5 13420H,Intel,Core,Core I5,13420H,H,8.0,12.0,4.0,4.0,NaN,16,1024,1920,1080,15.6,False,"15.6 inches, 1920 x 1080 pixels",Integrated Intel UHD Graphics,Intel,UHD,UHD Graphics,NaN,True,Windows,1.0,IdeaPad Slim 3,Thin & Light
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,34990,51,7th Gen AMD Ryzen 3 7320U,AMD,Ryzen,Ryzen 3,7320U,U,4.0,8.0,NaN,NaN,NaN,16,512,1920,1080,15.6,False,"15.6 inches, 1920 x 1080 pixels",AMD Radeon AMD,AMD,Radeon,Radeon,NaN,True,Windows,1.0,Vivobook Go 15,Thin & Light
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,56990,48,12th Gen Intel Core i7 1255U,Intel,Core,Core I7,1255U,U,10.0,12.0,2.0,8.0,NaN,16,512,1920,1080,14,False,"14 inches, 1920 x 1080 pixels",Integrated Intel Iris Xe Graphics,Intel,Iris Xe,Iris Xe Graphics,NaN,True,Windows,1.0,V14 G3,General
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,69990,52,Intel Core 5 120U,Intel,Core,Core 5,120U,U,10.0,12.0,2.0,8.0,NaN,16,512,1920,1080,14,False,"14 inches, 1920 x 1080 pixels",Intel UHD Graphics,Intel,UHD,UHD Graphics,NaN,True,Windows,1.0,DC 14250,General

In [ ]:
df_final.to_csv("../data/processed/laptops_cleaned.csv", index=False)

In [1016]:
mask = df1["processor_brand"].str.lower() == "AMD"

df1.loc[mask, ["p_cores", "e_cores", "lp_e_cores"]] = None

In [1019]:
df1["e_cores"].isna().sum()

np.int64(312)

In [1020]:
df1.isna().sum()

brand                 0
model                 0
price                 0
rating                0
processor             0
cores                15
ram                   0
storage               0
display_width         0
display_height        0
display_size          0
display               0
graphics              6
os                    0
warranty              0
processor_brand       0
processor_family      0
processor_series      0
processor_model       0
processor_suffix    132
core_count            0
threads_count         0
p_cores             290
e_cores             312
lp_e_cores          830
gpu_brand             6
gpu_series            6
gpu_model             6
gpu_vram            703
is_integrated         6
series_name           0
device_type           0
has_touchscreen       0
dtype: int64

In [1025]:
df1[df1["p_cores"].notnull() & df1["e_cores"].isnull()]

,brand,model,price,rating,processor,cores,ram,storage,display_width,display_height,display_size,display,graphics,os,warranty,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,series_name,device_type,has_touchscreen
101,dell,Dell 14 Plus DB14250 ODB1425020801RINU1 Laptop...,112990,66,Intel Core Ultra 7 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,2560,1440,14,"14 inches, 2560 x 1440 pixels",Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,14 Plus,General,False
106,dell,Dell 14 Plus 2-in-1 ODB0425020301RINU1 Touch L...,107900,69,Intel Core Ultra 7 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",Intel Arc Graphics,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,14 Plus 2-in-1,Convertible,True
175,dell,Dell 14 Plus 2-in-1 Touch Laptop (Intel Core U...,85990,68,Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",Intel Arc Graphics,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,14 Plus 2-in-1 Touch,Convertible,True
183,hp,HP OmniBook X Flip 14-fm0099TU Next Gen AI Lap...,104990,72,Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,1024,2880,1800,14,"14 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc 130V GPU (8GB),Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc 130V GPU (8GB),8.0,False,OmniBook X Flip,Convertible,True
202,hp,HP OmniBook X Flip 14-fm0100TU Next Gen AI Lap...,116499,74,Intel Core Ultra 7 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,1024,2880,1800,14,"14 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc 140V GPU (8GB),Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc 140V GPU (8GB),8.0,False,OmniBook X Flip,Convertible,True
450,lenovo,Lenovo Yoga 7 2-in-1 83JQ000XIN Laptop (Intel ...,110990,66,Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,1024,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",Integrated Intel Arc Graphics 140V,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics 140V,NaN,True,Yoga 7 2-in-1,Convertible,True
476,lenovo,Lenovo Yoga Slim 7 Aura Edition 83JX005FIN Lap...,102490,64,Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,1024,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",Integrated Intel Arc Graphics,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,Yoga Slim 7 Aura Edition,Convertible,True
538,asus,Asus Expertbook P5 P5405CSA-NZ0583WS Laptop (I...,84990,68,Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",32,1024,2560,1600,14,"14 inches, 2560 x 1600 pixels",Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,Expertbook P5,General,False
567,hp,HP OmniBook X Flip 14-fm0058TU Next Gen AI PC ...,94087,71,Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,2880,1800,14,"14 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc Graphics,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,OmniBook X Flip,Convertible,True
569,hp,HP OmniBook X Flip 14-fm0026TU Next Gen AI PC ...,114499,70,Intel Core Ultra 7 Series 2 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,2880,1800,14,"14 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc Graphics,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,OmniBook X Flip,Convertible,True
627,samsung,Samsung Galaxy Book 5 Pro NP940XHA-LG1IN Lapto...,131990,70,Intel Core Ultra 5 Series 2 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,2880,1800,14,"14 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc 130V GPU,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc 130V GPU,NaN,True,Galaxy Book 5 Pro,General,True
630,samsung,Samsung Galaxy Book 5 Pro 360 np960qha-kg3in L...,155990,68,5th Gen Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,2880,1800,16,"16 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc 130V GPU,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc 130V GPU,NaN,True,Galaxy Book 5 Pro 360,General,True
631,samsung,Samsung Galaxy Book 5 360 np750qha-lg1in Lapto...,107990,61,5th Gen Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels, Touch Screen",Intel Arc Graphics 130V,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics 130V,NaN,True,Galaxy Book 5 360,General,True
633,samsung,Samsung Galaxy Book 5 Pro 360 np960qha-kg1in L...,163990,71,Intel Core Ultra 7 Series 2 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,2880,1800,16,"16 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc 140V GPU,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc 140V GPU,NaN,True,Galaxy Book 5 Pro 360,General,True
634,samsung,Samsung Galaxy Book 5 Pro np940xha-lg2in Lapto...,139990,70,Intel Core Ultra 7 Series 2 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,2880,1800,14,"14 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc 140V GPU,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc 140V GPU,NaN,True,Galaxy Book 5 Pro,General,True
636,samsung,Samsung Galaxy Book 5 360 NP750QHA-LG3IN Lapto...,134999,70,Intel Core Ultra 7 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,1024,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels, Touch Screen",Intel Arc Graphics 140V,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics 140V,NaN,True,Galaxy Book 5 360,General,True
637,samsung,Samsung Galaxy Book 5 360 NP750QHA-LG2IN Lapto...,122990,69,Intel Core Ultra 7 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,1920,1080,15.6,"15.6 inches, 1920 x 1080 pixels, Touch Screen",Intel Arc Graphics 140V,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics 140V,NaN,True,Galaxy Book 5 360,General,True
678,asus,Asus Vivobook S 14 OLED 2025 S5406SA-QD094WS L...,99990,65,Intel Core Ultra 7 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,Vivobook S 14 OLED 2025,Thin & Light,False
679,asus,Asus Vivobook S 14 OLED 2025 S5406SA-QD098WS L...,84990,59,5th Gen Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels",Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,Vivobook S 14 OLED 2025,Thin & Light,False
682,asus,Asus Vivobook 14 Flip TP3407SA-QL025WS Laptop ...,101990,66,Intel Core Ultra 7 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,Vivobook 14 Flip,Convertible,True
697,asus,Asus Vivobook 14 Flip TP3407SA-QL024WS Laptop ...,84990,60,5th Gen Intel Core Ultra 5 226V,"Octa Core (4P + 4LP-E), 8 Threads",16,512,1920,1200,14,"14 inches, 1920 x 1200 pixels, Touch Screen",Intel Integrated Arc,Windows,1.0,Intel,Core Ultra,Core Ultra 5,226V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc Graphics,NaN,True,Vivobook 14 Flip,Convertible,True
860,samsung,Samsung Galaxy Book 5 Pro NP940XHA-LG4IN Lapto...,145990,71,Intel Core Ultra 7 Series 2 256V,"Octa Core (4P + 4LP-E), 8 Threads",16,1024,2880,1800,14,"14 inches, 2880 x 1800 pixels, Touch Screen",Intel Arc 140V GPU,Windows,1.0,Intel,Core Ultra,Core Ultra 7,256V,V,8.0,8.0,4.0,NaN,4.0,Intel,Arc,Arc 140V GPU,NaN,True,Galaxy Book 5 Pro,General,True

In [1026]:
df1.columns

Index(['brand', 'model', 'price', 'rating', 'processor', 'cores', 'ram',
       'storage', 'display_width', 'display_height', 'display_size', 'display',
       'graphics', 'os', 'warranty', 'processor_brand', 'processor_family',
       'processor_series', 'processor_model', 'processor_suffix', 'core_count',
       'threads_count', 'p_cores', 'e_cores', 'lp_e_cores', 'gpu_brand',
       'gpu_series', 'gpu_model', 'gpu_vram', 'is_integrated', 'series_name',
       'device_type', 'has_touchscreen'],
      dtype='object')

In [ ]:
import re

def clean_gpu_model(model):
    if pd.isna(model):
        return model

    s = str(model)

    # Remove patterns like "(8GB)", "(16GB)", "(4 GB)", "( 8 gb )"
    s = re.sub(r"\(\s*\d+\s*gb\s*\)", "", s, flags=re.IGNORECASE).strip()

    # Remove trailing/messy spaces and duplicate spaces
    s = re.sub(r"\s+", " ", s).strip()

    return s

df1["gpu_model"] = df["gpu_model"].apply(clean_gpu_model)

In [1067]:
df1["gpu_series"].unique()

array(['GeForce RTX', 'UHD', 'Radeon', 'Iris Xe', None,
       'Integrated Graphics', 'HD', 'Arc', 'Apple GPU', 'Adreno', 'RTX',
       'GeForce MX'], dtype=object)

In [1057]:
import re

gpu_map = {
    # NVIDIA
    "rtx 5060": "RTX 5060",
    "rtx 5050": "RTX 5050",
    "rtx 4050": "RTX 4050",
    "rtx 3050": "RTX 3050",
    "rtx 3050a": "RTX 3050A",
    "rtx 4060": "RTX 4060",
    "rtx 4070": "RTX 4070",
    "rtx 4080": "RTX 4080",
    "rtx 4090": "RTX 4090",
    "rtx 5070": "RTX 5070",
    "rtx 5070ti": "RTX 5070 Ti",
    "rtx 5080": "RTX 5080",
    "rtx 5090": "RTX 5090",
    "rtx 2000": "RTX 2000",
    "rtx 1000": "RTX 1000",
    "rtx a1000": "RTX A1000",
    "rtx a500": "RTX A500",
    "rtx 3000": "RTX 3000",

    # AMD integrated
    "660m": "Radeon 660M",
    "680m": "Radeon 680M",
    "820m": "Radeon 820M",
    "840m": "Radeon 840M",
    "860m": "Radeon 860M",
    "880m": "Radeon 880M",
    "amd graphics": "Radeon Graphics",
    "radeon": "Radeon",

    # AMD dedicated
    "rx 6500m": "RX 6500M",

    # Intel
    "iris xe": "Iris Xe",
    "intel integrated graphics": "Intel Integrated",
    "arc gpu": "Intel Arc",
    "arc graphics": "Intel Arc",
    "arc 130v": "Arc 130V",
    "arc 140v": "Arc 140V",
    "arc 140t": "Arc 140T",
    "uhd graphics": "UHD Graphics",
    "hd graphics": "HD Graphics",

    # Qualcomm
    "adreno adreno": "Adreno",
    "adreno gpu": "Adreno",
    "adreno": "Adreno",

    # Apple
    "10 core gpu": "Apple 10-Core GPU",
    "10-core gpu": "Apple 10-Core GPU",
    "20 core gpu": "Apple 20-Core GPU",
    "32 core gpu": "Apple 32-Core GPU",
    "16 core gpu": "Apple 16-Core GPU",
    "apple 10 core gpu": "Apple 10-Core GPU",
    "apple 8 core gpu": "Apple 8-Core GPU"
}

def normalize_gpu(model):
    if pd.isna(model):
        return None
    s = model.lower().strip()

    # remove VRAM if still present
    s = re.sub(r"\(\s*\d+\s*gb\s*\)", "", s).strip()

    for k, v in gpu_map.items():
        if k in s:
            return v

    return model.strip()

df1["gpu_model"] = df1["gpu_model"].apply(normalize_gpu)

In [1074]:
df1[df1["gpu_series"]=="Graphics"]

Empty DataFrame
Columns: [brand, model, price, rating, processor, cores, ram, storage, display_width, display_height, display_size, display, graphics, os, warranty, processor_brand, processor_family, processor_series, processor_model, processor_suffix, core_count, threads_count, p_cores, e_cores, lp_e_cores, gpu_brand, gpu_series, gpu_model, gpu_vram, is_integrated, series_name, device_type, has_touchscreen]
Index: []

In [ ]:
# df1.to_csv("test.csv", index=False)  # Intermediate test file - commented out

In [1066]:
# ---- AMD GPU clean-up ----
mask_amd = df1["gpu_brand"].eq("AMD")

# 1) "Graphics" series for AMD -> Radeon
df1.loc[mask_amd & df1["gpu_series"].eq("Graphics"), "gpu_series"] = "Radeon"

# 2) Generic "Graphics" model for AMD -> Radeon Graphics
df1.loc[mask_amd & df1["gpu_model"].eq("Graphics"), "gpu_model"] = "Radeon Graphics"

# 3) If AMD but series is still missing, treat as Radeon iGPU
df1.loc[mask_amd & df1["gpu_series"].isna(), "gpu_series"] = "Radeon"

# 4) If AMD but model is missing, and looks like integrated graphics in raw text,
#    fill with "Radeon Graphics"
mask_amd_igpu = (
    mask_amd &
    df1["gpu_model"].isna() &
    df1["graphics"].str.contains("graphics|integrated", case=False, na=False)
)
df1.loc[mask_amd_igpu, "gpu_model"] = "Radeon Graphics"

# 5) (Optional) strip VRAM like "(8GB)" from the model if it appears there
df1["gpu_model"] = df1["gpu_model"].str.replace(r"\s*\(\d+\s*GB\)", "", regex=True)
df1["gpu_model"] = df1["gpu_model"].str.strip()

In [1078]:
# Normalize AMD Radeon duplicates
mask_amd = df1["gpu_brand"].eq("AMD")

# Clean series
df1.loc[mask_amd, "gpu_series"] = "Radeon"

# Clean model
df1.loc[mask_amd, "gpu_model"] = "Radeon Graphics"

# Always integrated unless VRAM > 0
df1.loc[mask_amd & df1["gpu_vram"].isna(), "is_integrated"] = True

In [1082]:
# UHD / HD / Intel Integrated variants
mask_uhd = df1['graphics'].str.contains(
    r'UHD|HD Graphics|Intel Graphics|Integrated Intel UHD|Intel Integrated$', 
    case=False, na=False
)

df1.loc[mask_uhd, 'gpu_brand'] = 'Intel'
df1.loc[mask_uhd, 'gpu_series'] = 'UHD'
df1.loc[mask_uhd, 'gpu_model'] = 'UHD Graphics'
df1.loc[mask_uhd, 'is_integrated'] = True


# Iris Xe
mask_xe = df1['graphics'].str.contains(r'Iris Xe', case=False, na=False)

df1.loc[mask_xe, 'gpu_brand'] = 'Intel'
df1.loc[mask_xe, 'gpu_series'] = 'Iris Xe'
df1.loc[mask_xe, 'gpu_model'] = 'Iris Xe Graphics'
df1.loc[mask_xe, 'is_integrated'] = True


# Intel Arc (Integrated low-power versions)
mask_arc = df1['graphics'].str.contains(r'Arc', case=False, na=False)

df1.loc[mask_arc, 'gpu_brand'] = 'Intel'
df1.loc[mask_arc, 'gpu_series'] = 'Arc'
df1.loc[mask_arc, 'gpu_model'] = 'Arc Graphics'
df1.loc[mask_arc, 'is_integrated'] = df1['gpu_vram'].isna()  # integrated if vram is missing

In [1085]:
df1["gpu_brand"].unique()

array(['NVIDIA', 'Intel', 'AMD', None, 'Apple', 'Qualcomm'], dtype=object)

In [1086]:
df1["gpu_series"].unique()

array(['GeForce RTX', 'UHD', 'Radeon', 'Iris Xe', None, 'Arc',
       'Apple GPU', 'Adreno', 'RTX', 'Integrated Graphics', 'GeForce MX'],
      dtype=object)

In [1087]:
df1["gpu_model"].unique()

array(['RTX 5060', 'UHD Graphics', 'Radeon Graphics', 'Iris Xe Graphics',
       None, 'RTX 3050', 'RTX 4050', 'RTX 5050', 'RTX 5090', 'RTX 5080',
       'RTX 4060', 'Arc Graphics', 'Apple 10-Core GPU', 'Adreno',
       'RTX 5070', 'RTX 500', 'RTX 2000', 'RTX 1000', 'RTX A1000',
       'RTX 2050', 'RTX A500', 'Intel Integrated', 'RTX 4070', 'RTX 3000',
       'RTX 4080', 'MX 230', 'RTX 3070', 'RTX 4090', 'Apple 32-Core GPU',
       'Apple 20-Core GPU', 'Apple 16-Core GPU', 'Apple 8-Core GPU'],
      dtype=object)

In [1088]:
import re
import numpy as np

def clean_gpu(row):
    raw = str(row["graphics"]).strip()

    # Handle missing
    if raw.lower() in ["nan", "none", ""]:
        return pd.Series([None, None, None, None])

    text = raw.lower()

    # ===== NVIDIA =====
    if "rtx" in text or "nvidia" in text or "geforce" in text:
        brand = "NVIDIA"

        # Series
        if "rtx" in text:
            series = "GeForce RTX"
        elif "mx" in text:
            series = "GeForce MX"
        else:
            series = "GeForce"

        # GPU Model extraction
        model = re.findall(r"(rtx\s?\d+\w*|mx\s?\d+|rtx\s?a?\d+\w*)", text, flags=re.I)
        model = model[0].upper().replace(" ", "") if model else None

        # Remove memory part ("8GB", etc.)
        if model:
            model = model.replace("GB", "").strip()

        is_integrated = False

        return pd.Series([brand, series, model, is_integrated])

    # ===== AMD =====
    if "amd" in text or "radeon" in text:
        brand = "AMD"

        # Integrated AMD (e.g. Radeon 820M, Radeon Graphics)
        if "radeon" in text and not any(x in text for x in ["rx", "m", "xt", "pro", "vega"]):
            series = "Radeon"
            model = "Radeon Graphics"
            is_integrated = True
        else:
            # Discrete AMD GPU (RX / PRO)
            series = "Radeon"
            model_match = re.findall(r"(rx\s?\d+\w*)", text, flags=re.I)
            model = model_match[0].upper().replace(" ", "") if model_match else "Radeon"
            is_integrated = False

        return pd.Series([brand, series, model, is_integrated])

    # ===== INTEL =====
    if "intel" in text or "iris" in text or "uhd" in text or "hd graphics" in text or "integrated graphics" in text:

        brand = "Intel"

        # Series
        if "iris" in text:
            series = "Iris Xe"
            model = "Iris Xe Graphics"
        elif "uhd" in text:
            series = "UHD"
            model = "UHD Graphics"
        elif "hd graphics" in text:
            series = "HD"
            model = "HD Graphics"
        elif "arc" in text:
            series = "Arc"
            model = "Arc Graphics"
        else:
            # Generic "Intel Integrated" / "Intel Graphics"
            series = "Integrated Graphics"
            model = "Integrated Graphics"

        is_integrated = True

        return pd.Series([brand, series, model, is_integrated])

    # ===== Qualcomm Adreno =====
    if "adreno" in text:
        brand = "Qualcomm"
        series = "Adreno"
        model = "Adreno GPU"
        is_integrated = True
        return pd.Series([brand, series, model, is_integrated])

    # ===== Apple GPU =====
    if "apple" in text:
        brand = "Apple"
        series = "Apple GPU"

        # Extract model: "10-core GPU", "8-core GPU"
        model = re.findall(r"(\d+\-?core gpu)", text)
        model = model[0].title() if model else "Apple GPU"

        is_integrated = True
        return pd.Series([brand, series, model, is_integrated])

    # ===== Fallback =====
    return pd.Series([None, None, None, None])


# ==== APPLY CLEANING ====
df1[["gpu_brand", "gpu_series", "gpu_model", "is_integrated"]] = df1.apply(clean_gpu, axis=1)

In [1100]:
# --- define the final useful columns ---
final_columns = [
    "brand",
    "model",
    "series_name",
    "device_type",
    "price",
    "rating",
    
    "processor_brand",
    "processor_family",
    "processor_series",
    "processor_model",
    "processor_suffix",
    "core_count",
    "threads_count",
    "p_cores",
    "e_cores",
    "lp_e_cores",

    "ram",
    "storage",

    "display_width",
    "display_height",
    "display_size",
    "gpu_brand",
    "gpu_series",
    "gpu_model",
    "gpu_vram",
    "is_integrated",

    "os",
    "warranty",

]

# --- keep only available columns (ignore missing ones safely) ---
final_columns = [col for col in final_columns if col in df1.columns]

# --- Create final cleaned dataframe ---
df_final = df1[final_columns].copy()

df_final.head()

,brand,model,series_name,device_type,price,rating,processor_brand,processor_family,processor_series,processor_model,processor_suffix,core_count,threads_count,p_cores,e_cores,lp_e_cores,ram,storage,display_width,display_height,display_size,gpu_brand,gpu_series,gpu_model,gpu_vram,is_integrated,os,warranty
0,lenovo,Lenovo Legion Pro 5 16IAX10 83F3007CIN Gaming ...,Legion Pro 5,Gaming,189990,84,Intel,Core Ultra,Core Ultra 7,255HX,HX,20.0,20.0,8.0,12.0,NaN,32,1024,2560,1600,16,NVIDIA,GeForce RTX,RTX 5060,8.0,False,Windows,1.0
1,lenovo,Lenovo IdeaPad Slim 3 83K100HSIN Laptop (13th ...,IdeaPad Slim 3,Thin & Light,62350,54,Intel,Core,Core I5,13420H,H,8.0,12.0,4.0,4.0,NaN,16,1024,1920,1080,15.6,Intel,UHD,UHD Graphics,NaN,True,Windows,1.0
2,asus,Asus Vivobook Go 15 E1504FA-BQ2343WS Laptop (A...,Vivobook Go 15,Thin & Light,34990,51,AMD,Ryzen,Ryzen 3,7320U,U,4.0,8.0,NaN,NaN,NaN,16,512,1920,1080,15.6,AMD,Radeon,Radeon,NaN,False,Windows,1.0
3,lenovo,Lenovo V14 G3 82TS00JGUS Laptop (12th Gen Core...,V14 G3,General,56990,48,Intel,Core,Core I7,1255U,U,10.0,12.0,2.0,8.0,NaN,16,512,1920,1080,14,Intel,Iris Xe,Iris Xe Graphics,NaN,True,Windows,1.0
4,dell,Dell DC 14250 ODC1425000401RINS1 Laptop (Intel...,DC 14250,General,69990,52,Intel,Core,Core 5,120U,U,10.0,12.0,2.0,8.0,NaN,16,512,1920,1080,14,Intel,UHD,UHD Graphics,NaN,True,Windows,1.0

In [ ]:
df_final.to_csv("../data/processed/laptops_cleaned.csv", index=False)

In [1092]:
df1["gpu_model"].unique()

array(['RTX5060', 'UHD Graphics', 'Radeon', 'Iris Xe Graphics', None,
       'RTX3050', 'RTX4050', 'Integrated Graphics', 'RTX5050',
       'HD Graphics', 'RTX5090', 'RTX5080', 'RTX4060', 'Arc Graphics',
       'Adreno GPU', 'RTX5070', 'RTX500', 'RTX2000', 'RTX1000',
       'RTX3050A', 'RTXA1000', 'RTX2050', 'RTXA500', 'RTX4070', 'RTX3000',
       'RTX5070TI', 'RX6500M', 'RTX4080', 'MX230', 'Apple GPU', 'RTX3070',
       'RTX4090'], dtype=object)

In [1093]:
df1["gpu_series"].unique()

array(['GeForce RTX', 'UHD', 'Radeon', 'Iris Xe', None,
       'Integrated Graphics', 'HD', 'Arc', 'Adreno', 'GeForce MX',
       'Apple GPU'], dtype=object)

In [1094]:
import re

def fix_gpu_model_spacing(model):
    if model is None or str(model).lower() == "none" or str(model).strip() == "":
        return model
    
    m = str(model)

    # === NVIDIA RTX ===
    # RTX4060 → RTX 4060
    m = re.sub(r"RTX\s?(\d+)", r"RTX \1", m, flags=re.I)

    # RTXA500 → RTX A500
    m = re.sub(r"RTX\s?A\s?(\d+)", r"RTX A\1", m, flags=re.I)
    m = re.sub(r"RTXA\s?(\d+)", r"RTX A\1", m, flags=re.I)

    # RTX3050A → RTX 3050A
    m = re.sub(r"RTX\s?(\d+)(A)", r"RTX \1\2", m, flags=re.I)

    # RTX5070TI → RTX 5070 Ti
    m = re.sub(r"RTX\s?(\d+)\s?TI", r"RTX \1 Ti", m, flags=re.I)

    # === AMD RX ===
    # RX6500M → RX 6500M
    m = re.sub(r"RX\s?(\d+\w*)", r"RX \1", m, flags=re.I)

    # === NVIDIA MX ===
    # MX230 → MX 230
    m = re.sub(r"MX\s?(\d+)", r"MX \1", m, flags=re.I)

    # === NVIDIA RTX (clean double spaces) ===
    m = re.sub(r"\s+", " ", m).strip()

    return m

df1["gpu_model"] = df1["gpu_model"].apply(fix_gpu_model_spacing)

In [1099]:
import re

def refine_gpu_row(row):
    brand   = row["gpu_brand"]
    series  = row["gpu_series"]
    model   = row["gpu_model"]
    text    = str(row["graphics"]) if "graphics" in row else ""

    # Default: keep current values
    new_series = series
    new_model  = model

    # ---------- AMD: recover RX models like RX 6500M ----------
    if brand == "AMD":
        m_rx = re.search(r"(RX\s*\d+\w*)", text, flags=re.IGNORECASE)
        if m_rx:
            # e.g. "RX 6500M" -> "RX 6500M"
            new_model = m_rx.group(1).upper().replace("  ", " ")
            # optionally mark series as Radeon RX (if you want more granularity)
            # new_series = "Radeon RX"
            return new_series, new_model

    # ---------- Intel Arc: keep 130V / 140V model codes ----------
    if brand == "Intel" and series == "Arc":
        # e.g. "Arc 130V GPU (8GB)", "Arc 140T GPU"
        m_arc = re.search(r"Arc\s+(\d+\w*)", text, flags=re.IGNORECASE)
        if m_arc:
            code = m_arc.group(1).upper()
            new_model = f"Arc {code} GPU"
            return new_series, new_model

    # ---------- Qualcomm Adreno ----------
    if brand == "Qualcomm":
        # Normalize everything to "Adreno GPU"
        return "Adreno", "Adreno GPU"

    # ---------- Intel integrated generic ----------
    if brand == "Intel" and series == "Integrated Graphics":
        # Clean up model like "Intel Integrated" -> "Integrated Graphics"
        return new_series, "Integrated Graphics"

    # ---------- Apple GPU names ----------
    if brand == "Apple" and isinstance(model, str):
        # Normalize "10-Core GPU" -> "10 Core GPU", keep "Apple " prefix
        # ensure we always have "Core" with a space, not "Core-"
        m_core = re.search(r"(\d+)\s*-?\s*Core", model, flags=re.IGNORECASE)
        if m_core:
            cores = m_core.group(1)
            new_model = f"Apple {cores} Core GPU"
        else:
            # fallback: keep as is but replace "-Core" with " Core"
            new_model = model.replace("-Core", " Core")
        return new_series, new_model

    # Default: return existing values
    return new_series, new_model

# ---- Apply refinement in-place ----
df1["gpu_series"], df1["gpu_model"] = zip(*df1.apply(refine_gpu_row, axis=1))

In [1102]:
df1["gpu_model"].unique()

array(['RTX 5060', 'UHD Graphics', 'Radeon', 'Iris Xe Graphics', None,
       'RTX 3050', 'RTX 4050', 'Integrated Graphics', 'RTX 5050',
       'HD Graphics', 'RTX 5090', 'RTX 5080', 'RTX 4060', 'Arc Graphics',
       'Adreno GPU', 'RTX 5070', 'RTX 500', 'RTX 2000', 'RTX 1000',
       'RTX 3050A', 'RTX A1000', 'RTX 2050', 'Arc 140T GPU', 'RTX A500',
       'RTX 4070', 'Arc 130V GPU', 'Arc 140V GPU', 'RTX 3000',
       'RTX 5070 Ti', 'Arc 140 GPU', 'RX 6500M', 'RTX 4080', 'MX 230',
       'Apple GPU', 'RTX 3070', 'RTX 4090'], dtype=object)

In [1103]:
df1["gpu_series"].unique()

array(['GeForce RTX', 'UHD', 'Radeon', 'Iris Xe', None,
       'Integrated Graphics', 'HD', 'Arc', 'Adreno', 'GeForce MX',
       'Apple GPU'], dtype=object)